--[[
                                ----o----(||)----oo----(||)----o----

                                                Runes
                                         Localisation Module

                                       v1.39 - 23rd March 2024
                                Copyright (C) Taraezor / Chris Birch
                                         All Rights Reserved

                                ----o----(||)----oo----(||)----o----
]]

local _, ns = ...
L = {}
ns.L = L

ns.locale = GetLocale()

ns.realm = GetNormalizedRealmName() -- On a fresh login this will return null
ns.oceania = { AmanThul = true, Barthilas = true, Caelestrasz = true, DathRemar = true,
			Dreadmaul = true, Frostmourne = true, Gundrak = true, JubeiThos = true, 
			Khazgoroth = true, Nagrand = true, Saurfang = true, Thaurissan = true,
			-- The following are Classic 1.15.x
			Yojamba = true, Remulos = true, Arugal = true, Felstriker = true,
			-- The following are Seasonal Classic 1.15.x
			Penance = true, Shadowstrike = true }
if ns.oceania[ ns.realm ] then
	ns.locale = "enGB"
end

setmetatable( L, { __index = function( L, key ) return key end } )

-- Firstly, translations I often use in all my AddOns

if ns.locale == "deDE" then
	ns.L["Character"] = "Charakter"
	ns.L["Account"] = "Accountweiter"
	ns.L["Completed"] = "Abgeschlossen"
	ns.L["Not Completed"] = "Nicht Abgeschlossen"
	ns.L["Options"] = "Optionen"
	ns.L["Map Pin Size"] = "Pin-Größe"
	ns.L["The Map Pin Size"] = "Die Größe der Karten-Pins"
	ns.L["Map Pin Alpha"] = "Kartenpin Alpha"
	ns.L["The alpha transparency of the map pins"] = "Die Alpha-Transparenz der Karten-Pins"
	ns.L["Show Coordinates"] = "Koordinaten anzeigen"
	ns.L["Show Coordinates Description"] = "Zeigen sie die koordinaten in QuickInfos auf "
		.."der Weltkarte und auf der Minikarte an"
	ns.L["Map Pin Selections"] = "Karten-Pin-Auswahl"
	ns.L["Gold"] = "Gold"
	ns.L["Red"] = "Rot"
	ns.L["Blue"] = "Blau"
	ns.L["Green"] = "Grün"
	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Kreuz"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Zahnrad"
	ns.L["White"] = "Weiß"
	ns.L["Purple"] = "Lila"
	ns.L["Yellow"] = "Gelb"
	ns.L["Grey"] = "Grau"
	ns.L["Mana Orb"] = "Manakugel"
	ns.L["Phasing"] = "Synchronisieren"
	ns.L["Raptor egg"] = "Raptor-Ei"
	ns.L["Stars"] = "Sternen"
	ns.L["Screw"] = "Schraube"
	ns.L["Left"] = "Links"
	ns.L["Right"] = "Rechts"
	ns.L["Try later"] = "Derzeit nicht möglich. Versuche es späte"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["Character"] = "Personaje"
	ns.L["Account"] = "la Cuenta"
	ns.L["Completed"] = "Completado"
	ns.L["Not Completed"] = ( ns.locale == "esES" ) and "Sin Completar" or "Incompleto"
	ns.L["Options"] = "Opciones"
	ns.L["Map Pin Size"] = "Tamaño de alfiler"
	ns.L["The Map Pin Size"] = "Tamaño de los pines del mapa"
	ns.L["Map Pin Alpha"] = "Alfa de los pines del mapa"
	ns.L["The alpha transparency of the map pins"] = "La transparencia alfa de los pines del mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Mostrar coordenadas en información sobre "
		.."herramientas en el mapa del mundo y en el minimapa"
	ns.L["Map Pin Selections"] = "Selecciones de pines de mapa"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rojo"
	ns.L["Blue"] = "Azul"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Anillo"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Escarcha"
	ns.L["Cogwheel"] = "Rueda dentada"
	ns.L["White"] = "Blanco"
	ns.L["Purple"] = "Púrpura"
	ns.L["Yellow"] = "Amarillo"
	ns.L["Grey"] = "Gris"
	ns.L["Mana Orb"] = "Orbe de maná"
	ns.L["Phasing"] = "Sincronización"	
	ns.L["Raptor egg"] = "Huevo de raptor"	
	ns.L["Stars"] = "Estrellas"
	ns.L["Screw"] = "Tornillo"
	ns.L["Left"] = "Izquierda"
	ns.L["Right"] = "Derecha"
	ns.L["Try later"] = "No es posible en este momento. Intenta más tarde"

elseif ns.locale == "frFR" then
	ns.L["Character"] = "Personnage"
	ns.L["Account"] = "le Compte"
	ns.L["Completed"] = "Achevé"
	ns.L["Not Completed"] = "Non achevé"
	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Taille des épingles"
	ns.L["The Map Pin Size"] = "La taille des épingles de carte"
	ns.L["Map Pin Alpha"] = "Alpha des épingles de carte"
	ns.L["The alpha transparency of the map pins"] = "La transparence alpha des épingles de la carte"
	ns.L["Show Coordinates"] = "Afficher les coordonnées"
	ns.L["Show Coordinates Description"] = "Afficher les coordonnées\124r dans les info-bulles sur "
		.."la carte du monde et la mini-carte"
	ns.L["Map Pin Selections"] = "Sélections de broches de carte"
	ns.L["Gold"] = "Or"
	ns.L["Red"] = "Rouge"
	ns.L["Blue"] = "Bleue"
	ns.L["Green"] = "Vert"
	ns.L["Ring"] = "Bague"
	ns.L["Cross"] = "Traverser"
	ns.L["Diamond"] = "Diamant"
	ns.L["Frost"] = "Givre"
	ns.L["Cogwheel"] = "Roue dentée"
	ns.L["White"] = "Blanc"
	ns.L["Purple"] = "Violet"
	ns.L["Yellow"] = "Jaune"
	ns.L["Grey"] = "Gris"
	ns.L["Mana Orb"] = "Orbe de mana"
	ns.L["Phasing"] = "Synchronisation"
	ns.L["Raptor egg"] = "Œuf de Rapace"
	ns.L["Stars"] = "Étoiles"
	ns.L["Screw"] = "Vis"
	ns.L["Left"] = "Gauche"
	ns.L["Right"] = "Droite"
	ns.L["Try later"] = "Pas possible pour le moment. Essayer plus tard"

elseif ns.locale == "itIT" then
	ns.L["Character"] = "Personaggio"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completo"
	ns.L["Not Completed"] = "Non Compiuto"
	ns.L["Options"] = "Opzioni"
	ns.L["Map Pin Size"] = "Dimensione del pin"
	ns.L["The Map Pin Size"] = "La dimensione dei Pin della mappa"
	ns.L["Map Pin Alpha"] = "Mappa pin alfa"
	ns.L["The alpha transparency of the map pins"] = "La trasparenza alfa dei pin della mappa"
	ns.L["Show Coordinates"] = "Mostra coordinate"
	ns.L["Show Coordinates Description"] = "Visualizza le coordinate\124r nelle descrizioni "
		.."comandi sulla mappa del mondo e sulla minimappa"
	ns.L["Map Pin Selections"] = "Selezioni pin mappa"
	ns.L["Gold"] = "Oro"
	ns.L["Red"] = "Rosso"
	ns.L["Blue"] = "Blu"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Squillo"
	ns.L["Cross"] = "Attraverso"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gelo"
	ns.L["Cogwheel"] = "Ruota dentata"
	ns.L["White"] = "Bianca"
	ns.L["Purple"] = "Viola"
	ns.L["Yellow"] = "Giallo"
	ns.L["Grey"] = "Grigio"
	ns.L["Mana Orb"] = "Globo di Mana"
	ns.L["Phasing"] = "Sincronizzazione"
	ns.L["Raptor egg"] = "Raptor Uovo"
	ns.L["Stars"] = "Stelle"
	ns.L["Screw"] = "Vite"
	ns.L["Left"] = "Sinistra"
	ns.L["Right"] = "Destra"
	ns.L["Try later"] = "Non è possibile in questo momento. Prova più tardi"

elseif ns.locale == "koKR" then
	ns.L["Character"] = "캐릭터"
	ns.L["Account"] = "계정"
	ns.L["Completed"] = "완료"
	ns.L["Not Completed"] = "미완료"
	ns.L["Options"] = "설정"
	ns.L["Map Pin Size"] = "지도 핀의 크기"
	ns.L["The Map Pin Size"] = "지도 핀의 크기"
	ns.L["Map Pin Alpha"] = "지도 핀의 알파"
	ns.L["The alpha transparency of the map pins"] = "지도 핀의 알파 투명도"
	ns.L["Show Coordinates"] = "좌표 표시"
	ns.L["Show Coordinates Description"] = "세계지도 및 미니지도의 도구 설명에 좌표를 표시합니다."
	ns.L["Map Pin Selections"] = "지도 핀 선택"
	ns.L["Gold"] = "금"
	ns.L["Red"] = "빨간"
	ns.L["Blue"] = "푸른"
	ns.L["Green"] = "녹색"
	ns.L["Ring"] = "반지"
	ns.L["Cross"] = "십자가"
	ns.L["Diamond"] = "다이아몬드"
	ns.L["Frost"] = "냉기"
	ns.L["Cogwheel"] = "톱니 바퀴"
	ns.L["White"] = "화이트"
	ns.L["Purple"] = "보라색"
	ns.L["Yellow"] = "노랑"
	ns.L["Grey"] = "회색"
	ns.L["Mana Orb"] = "마나 보주"
	ns.L["Phasing"] = "동기화 중"
	ns.L["Raptor egg"] = "랩터의 알"
	ns.L["Stars"] = "별"
	ns.L["Screw"] = "나사"
	ns.L["Left"] = "왼쪽"
	ns.L["Right"] = "오른쪽"
	ns.L["Try later"] = "지금은 불가능합니다. 나중에 시도하세요"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["Character"] = "Personagem"
	ns.L["Account"] = "à Conta"
	ns.L["Completed"] = "Concluído"
	ns.L["Not Completed"] = "Não Concluído"
	ns.L["Options"] = "Opções"
	ns.L["Map Pin Size"] = "Tamanho do pino"
	ns.L["The Map Pin Size"] = "O tamanho dos pinos do mapa"
	ns.L["Map Pin Alpha"] = "Alfa dos pinos do mapa"
	ns.L["The alpha transparency of the map pins"] = "A transparência alfa dos pinos do mapa"
	ns.L["Show Coordinates"] = "Mostrar coordenadas"
	ns.L["Show Coordinates Description"] = "Exibir coordenadas\124r em dicas de ferramentas "
		.."no mapa mundial e no minimapa"
	ns.L["Map Pin Selections"] = "Seleções de pinos de mapa"
	ns.L["Gold"] = "Ouro"
	ns.L["Red"] = "Vermelho"
	ns.L["Blue"] = "Azul"
	ns.L["Green"] = "Verde"
	ns.L["Ring"] = "Anel"
	ns.L["Cross"] = "Cruz"
	ns.L["Diamond"] = "Diamante"
	ns.L["Frost"] = "Gélido"
	ns.L["Cogwheel"] = "Roda dentada"
	ns.L["White"] = "Branco"
	ns.L["Purple"] = "Roxa"
	ns.L["Yellow"] = "Amarelo"
	ns.L["Grey"] = "Cinzento"
	ns.L["Mana Orb"] = "Orbe de Mana"
	ns.L["Phasing"] = "Sincronização"
	ns.L["Raptor egg"] = "Ovo de raptor"
	ns.L["Stars"] = "Estrelas"
	ns.L["Screw"] = "Parafuso"
	ns.L["Left"] = "Esquerda"
	ns.L["Right"] = "Direita"
	ns.L["Try later"] = "Não é possível neste momento. Tente depois"

elseif ns.locale == "ruRU" then
	ns.L["Character"] = "Персонажа"
	ns.L["Account"] = "Счет"
	ns.L["Completed"] = "Выполнено"
	ns.L["Not Completed"] = "Не Выполнено"
	ns.L["Options"] = "Параметры"
	ns.L["Map Pin Size"] = "Размер булавки"
	ns.L["The Map Pin Size"] = "Размер булавок на карте"
	ns.L["Map Pin Alpha"] = "Альфа булавок карты"
	ns.L["The alpha transparency of the map pins"] = "Альфа-прозрачность булавок карты"
	ns.L["Show Coordinates"] = "Показать Координаты"
	ns.L["Show Coordinates Description"] = "Отображает координаты\124r во всплывающих "
		.."подсказках на карте мира и мини-карте"
	ns.L["Map Pin Selections"] = "Выбор булавки карты"
	ns.L["Gold"] = "Золото"
	ns.L["Red"] = "Красный"
	ns.L["Blue"] = "Синий"
	ns.L["Green"] = "Зеленый"
	ns.L["Ring"] = "Звенеть"
	ns.L["Cross"] = "Крест"
	ns.L["Diamond"] = "Ромб"
	ns.L["Frost"] = "Лед"
	ns.L["Cogwheel"] = "Зубчатое колесо"
	ns.L["White"] = "белый"
	ns.L["Purple"] = "Пурпурный"
	ns.L["Yellow"] = "Желтый"
	ns.L["Grey"] = "Серый"
	ns.L["Mana Orb"] = "Cфера маны"
	ns.L["Phasing"] = "Синхронизация"
	ns.L["Raptor egg"] = "Яйцо ящера"
	ns.L["Stars"] = "Звезды"
	ns.L["Screw"] = "Винт"
	ns.L["Left"] = "Налево"
	ns.L["Right"] = "Направо"
	ns.L["Try later"] = "В настоящее время это невозможно. Попробуй позже"

elseif ns.locale == "zhCN" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "账号"
	ns.L["Completed"] = "已完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Options"] = "选项"
	ns.L["Map Pin Size"] = "地图图钉的大小"
	ns.L["The Map Pin Size"] = "地图图钉的大小"
	ns.L["Map Pin Alpha"] = "地图图钉的透明度"
	ns.L["The alpha transparency of the map pins"] = "地图图钉的透明度"
	ns.L["Show Coordinates"] = "显示坐标"
	ns.L["Show Coordinates Description"] = "在世界地图和迷你地图上的工具提示中显示坐标"
	ns.L["Map Pin Selections"] = "地图图钉选择"
	ns.L["Gold"] = "金子"
	ns.L["Red"] = "红"
	ns.L["Blue"] = "蓝"
	ns.L["Green"] = "绿色"
	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "冰霜"
	ns.L["Cogwheel"] = "齿轮"
	ns.L["White"] = "白色"
	ns.L["Purple"] = "紫色"
	ns.L["Yellow"] = "黄色"
	ns.L["Grey"] = "灰色"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龙蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "拧"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Try later"] = "目前不可能。稍后再试"

elseif ns.locale == "zhTW" then
	ns.L["Character"] = "角色"
	ns.L["Account"] = "賬號"
	ns.L["Completed"] = "完成"
	ns.L["Not Completed"] = "未完成"
	ns.L["Options"] = "選項"
	ns.L["Map Pin Size"] = "地圖圖釘的大小"
	ns.L["The Map Pin Size"] = "地圖圖釘的大小"
	ns.L["Map Pin Alpha"] = "地圖圖釘的透明度"
	ns.L["The alpha transparency of the map pins"] = "地圖圖釘的透明度"
	ns.L["Show Coordinates"] = "顯示坐標"
	ns.L["Show Coordinates Description"] = "在世界地圖和迷你地圖上的工具提示中顯示坐標"
	ns.L["Map Pin Selections"] = "地圖圖釘選擇"
	ns.L["Gold"] = "金子"
	ns.L["Red"] = "紅"
	ns.L["Blue"] = "藍"
	ns.L["Green"] = "綠色"
	ns.L["Ring"] = "戒指"
	ns.L["Cross"] = "叉"
	ns.L["Diamond"] = "钻石"
	ns.L["Frost"] = "霜"
	ns.L["Cogwheel"] = "齒輪"
	ns.L["White"] = "白色"
	ns.L["Purple"] = "紫色"
	ns.L["Yellow"] = "黃色"
	ns.L["Grey"] = "灰色"
	ns.L["Mana Orb"] = "法力球"
	ns.L["Phasing"] = "同步"
	ns.L["Raptor egg"] = "迅猛龍蛋"
	ns.L["Stars"] = "星星"
	ns.L["Screw"] = "擰"
	ns.L["Left"] = "左"
	ns.L["Right"] = "右"
	ns.L["Try later"] = "目前不可能。稍後再試"

else
	ns.L["Character"] = "Character"
	ns.L["Account"] = "Account"
	ns.L["Completed"] = "Completed"
	ns.L["Not Completed"] = "Not Completed"
	ns.L["Options"] = "Options"
	ns.L["Map Pin Size"] = "Map Pin Size"
	ns.L["The Map Pin Size"] = "The Map Pin Size"
	ns.L["Map Pin Alpha"] = "Map Pin Alpha"
	ns.L["The alpha transparency of the map pins"] = "The alpha transparency of the map pins"
	ns.L["Show Coordinates"] = "Show Coordinates"
	ns.L["Show Coordinates Description"] = "Display coordinates in tooltips on the world map and the mini map"
	ns.L["Map Pin Selections"] = "Map Pin Selections"
	ns.L["Gold"] = "Gold"
	ns.L["Red"] = "Red"
	ns.L["Blue"] = "Blue"
	ns.L["Green"] = "Green"
	ns.L["Ring"] = "Ring"
	ns.L["Cross"] = "Cross"
	ns.L["Diamond"] = "Diamond"
	ns.L["Frost"] = "Frost"
	ns.L["Cogwheel"] = "Cogwheel"
	ns.L["White"] = "White"
	ns.L["Purple"] = "Purple"
	ns.L["Yellow"] = "Yellow"
	ns.L["Grey"] = ( ( ns.locale == "enUS" ) and "Gray" or "Grey" )
	ns.L["Mana Orb"] = "Mana Orb"
	ns.L["Phasing"] = "Phasing"
	ns.L["Raptor egg"] = "Raptor egg"
	ns.L["Stars"] = "Stars"
	ns.L["Screw"] = "Screw"
	ns.L["Left"] = "Left"
	ns.L["Right"] = "Right"
	ns.L["Try later"] = "Not possible at this time. Try later"
end

-- Translations specific to the Runes AddOn

if ns.locale == "deDE" then
	ns.L["AddOn Description"] = "Alle SoD-Runen. (Und mehr!)"
	ns.L["Arcane"] = "Arkane"
	ns.L["Demonic"] = "Dämonische"
	ns.L["Duty"] = "Pflicht"
	ns.L["Hide if learnt"] = "Verstecke dich, wenn die Rune gelernt wurde"
	ns.L["Map Pin"] = "Kartenpin"
	ns.L["Mjolnir"] = "Mjolnir"
	ns.L["Phase 1 Summary"] = "Zusammenfassung der Phase 1"
	ns.L["Phase 2 Summary"] = "Zusammenfassung der Phase 2"
	ns.L["Runes"] = "Runen"
	ns.L["Skill Book"] = "Fertigkeitsbuch"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "Furor von Sturmgrimm"
	ns.L["Lacerate"] = "Aufschlitzen"
	ns.L["Lifebloom"] = "Blühendes Leben"
	ns.L["Living Seed"] = "Samenkorn des Lebens"
	ns.L["Mangle"] = "Zerfleischen"
	ns.L["Savage Roar"] = "Wildes Brüllen"
	ns.L["Skull Bash"] = "Schädelstoß"
	ns.L["Starsurge"] = "Sternensog"
	ns.L["Sunfire"] = "Sonnenfeuer"
	ns.L["Survival of the Fittest"] = "Überleben des Stärkeren"
	ns.L["Wild Growth"] = "Wildwuchs"
	ns.L["Wild Strikes"] = "Wilde Stöße"
	-- Druid Phase 2
	ns.L["Berserk"] = "Berserker"
	ns.L["Deeper Wilds"] = "Tiefe Wildnis"
	ns.L["Dreamstate"] = "Traumzustand"
	ns.L["Eclipse"] = "Finsternis"
	ns.L["Enhanced Restoration"] = "Verbesserte Wiederherstellung"
	ns.L["King of the Jungle"] = "König des Dschungels"
	ns.L["Nourish"] = "Pflege"
	ns.L["Revive"] = "Wiederbelebung"
	ns.L["Survival Instincts"] = "Überlebensinstinkte"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "Meister der Tiere"
	ns.L["Carve"] = "Zerlegen"
	ns.L["Chimera Shot"] = "Schimärenschuss"
	ns.L["Cobra Strikes"] = "Kobrastöße"
	ns.L["Explosive Shot"] = "Explosivschuss"
	ns.L["Flanking Strike"] = "Flankenangriff"
	ns.L["Heart of the Lion"] = "Löwenherz"
	ns.L["Kill Command"] = "Tötungsbefehl"
	ns.L["Lone Wolf"] = "Einsamer Wolf"
	ns.L["Master Marksman"] = "Meister der Treffsicherheit"
	ns.L["Serpent Spread"] = "Schlangenspur"
	ns.L["Sniper Training"] = "Scharfschützentraining"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "Aspekt der Viper"
	ns.L["Dual Wield Specialization"] = "Beidhändigkeitsspezialisierung"
	ns.L["Expose Weakness"] = "Schwäche aufdecken"
	ns.L["Invigoration"] = "Kräftigung"
	ns.L["Melee Specialist"] = "Nahkampfspezialist"
	ns.L["Steady Shot"] = "Zuverlässiger Schuss"
	ns.L["Trap Launcher"] = "Fallenschleuder"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "Arkanschlag"
	ns.L["Arcane Surge"] = "Arkane Woge"
	ns.L["Burnout"] = "Feuerfontäne"
	ns.L["Enlightenment"] = "Erleuchtung"
	ns.L["Fingers of Frost"] = "Eisige Finger"
	ns.L["Ice Lance"] = "Eislanze"
	ns.L["Icy Veins"] = "Eisige Adern"
	ns.L["Living Bomb"] = "Lebende Bombe"
	ns.L["Living Flame"] = "Lebende Flamme"
	ns.L["Mass Regeneration"] = "Massenregeneration"
	ns.L["Regeneration"] = "Regeneration"
	ns.L["Rewind Time"] = "Zeit zurückdrehen"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "Hirnfrost"
	ns.L["Chronostatic Preservation"] = "Chronostatische Bewahrung"
	ns.L["Expanded Intellect"] = "Erweiterte Intelligenz"
	ns.L["Frostfire Bolt"] = "Frostfeuerblitz"
	ns.L["Hot Streak"] = "Kampfeshitze"
	ns.L["Missile Barrage"] = "Geschosssalve"
	ns.L["Spell Power"] = "Zaubermacht"
	ns.L["Spellfrost Bolt"] = "Zauberfrostblitz"
	-- Paladin Phase 1
	ns.L["Aegis"] = "Aegis"
	ns.L["Avenger's Shield"] = "Schild des Rächers"
	ns.L["Beacon of Light"] = "Flamme des Glaubens"
	ns.L["Crusader Strike"] = "Kreuzfahrerstoß"
	ns.L["Exorcist"] = "Exorzist"
	ns.L["Divine Sacrifice"] = "Heilige Opferung"
	ns.L["Divine Storm"] = "Göttlicher Sturm"
	ns.L["Hand of Reckoning"] = "Hand der Abrechnung"
	ns.L["Horn of Lordaeron"] = "Horn von Lordaeron"
	ns.L["Inspiration Exemplar"] = "Inspirationsvorbild"
	ns.L["Rebuke"] = "Zurechtweisung"
	ns.L["Seal of Martyrdom"] = "Siegel des Märtyrertums"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "Verbesserte Segen"
	ns.L["Enlightened Judgements"] = "Erleuchtete Richturteile"
	ns.L["Guarded by the Light"] = "Vom Licht behütet"
	ns.L["Infusion of Light"] = "Lichtinfusion"
	ns.L["Sacred Shield"] = "Geheiligter Schild"
	ns.L["Sheath of Light"] = "Ummantelung des Lichts"
	ns.L["The Art of War"] = "Die Kunst des Krieges"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "Kreis der Heilung"
	ns.L["Homunculi"] = "Homunculi"
	ns.L["Mind Sear"] = "Gedankenbrand"
	ns.L["Penance"] = "Sühne"
	ns.L["Power Word: Barrier"] = "Machtwort: Barriere"
	ns.L["Prayer of Mending"] = "Gebet der Besserung"
	ns.L["Serendipity"] = "Glücksfall"
	ns.L["Shadow Word: Death"] = "Schattenwort: Tod"
	ns.L["Shared Pain"] = "Geteilter Schmerz"
	ns.L["Strength of Soul"] = "Kraftvolle Seele"
	ns.L["Twisted Faith"] = "Okkultismus"
	ns.L["Void Plague"] = "Pest der Leere"
	-- Priest Phase 2
	ns.L["Dispersion"] = "Dispersion"
	ns.L["Empowered Renew"] = "Machterfüllte Erneuerung"
	ns.L["Increased Fortitude"] = "Erhöhte Seelenstärke"
	ns.L["Mind Spike"] = "Gedankenstachel"
	ns.L["Pain Suppression"] = "Schmerzunterdrückung"
	ns.L["Renewed Hope"] = "Erneuerte Hoffnung"
	ns.L["Shadowfiend"] = "Schattengeist"
	ns.L["Spirit of the Redeemer"] = "Geist des Erlösers"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "Zwischen die Augen"
	ns.L["Blade Dance"] = "Klingentanz"
	ns.L["Deadly Brew"] = "Tödliche Mischung"
	ns.L["Envenom"] = "Vergiften"
	ns.L["Just a Flesh Wound"] = "Nur eine Fleischwunde"
	ns.L["Main Gauche"] = "Parierdolch"
	ns.L["Mutilate"] = "Verstümmeln"
	ns.L["Quick Draw"] = "Pistolenheld"
	ns.L["Saber Slash"] = "Säbelschlitzer"
	ns.L["Shadowstrike"] = "Schattenschlag"
	ns.L["Slaughter from the Shadows"] = "Hinterhältiger Mord"
	ns.L["Shiv"] = "Tückische Klinge"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "Meister des hinterhältigen Angriffs"
	ns.L["Poisoned Knife"] = "Vergiftetes Messer"
	ns.L["Redirect"] = "Umleiten"
	ns.L["Rolling with the Punches"] = "Schläge abschwächen"
	ns.L["Shadowstep"] = "Schattenschritt"
	ns.L["Shuriken Toss"] = "Shurikenwurf"
	ns.L["Waylay"] = "Auflauern"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "Führung der Ahnen"
	ns.L["Dual Wield Specialization"] = "Beidhändigkeitsspezialisierung"
	ns.L["Earth Shield"] = "Erdschild"
	ns.L["Healing Rain"] = "Heilender Regen"
	ns.L["Lava Burst"] = "Lavaeruption"
	ns.L["Lava Lash"] = "Lavapeitsche"
	ns.L["Molten Blast"] = "Schmelzschlag"
	ns.L["Overload"] = "Überladung"
	ns.L["Shamanistic Rage"] = "Schamanistische Wut"
	ns.L["Shield Mastery"] = "Schildmeisterschaft"
	ns.L["Way of Earth"] = "Weg der Erde"
	ns.L["Water Shield"] = "Wasserschild"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "Erwachen der Ahnen"
	ns.L["Decoy Totem"] = "Täuschtotem"
	ns.L["Fire Nova"] = "Feuernova"
	ns.L["Maelstrom Weapon"] = "Waffe des Mahlstroms"
	ns.L["Power Surge"] = "Kraftwoge"
	ns.L["Spirit of the Alpha"] = "Geist des Alphas"
	ns.L["Totemic Projection"] = "Totemische Projektion"
	ns.L["Two-Handed Mastery"] = "Zweihandmeisterschaft"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "Chaosblitz"
	ns.L["Demonic Grace"] = "Dämonische Anmut"
	ns.L["Demonic Pact"] = "Dämonischer Pakt"
	ns.L["Demonic Tactics"] = "Dämonische Taktiken"
	ns.L["Everlasting Affliction"] = "Immerwährende Gebrechen"
	ns.L["Haunt"] = "Heimsuchung"
	ns.L["Incinerate"] = "Verbrennen"
	ns.L["Lake of Fire"] = "See des Feuers"
	ns.L["Master Channeler"] = "Meisterkanalisierer"
	ns.L["Metamorphosis"] = "Metamorphose"
	ns.L["Shadow Bolt Volley"] = "Schattenblitzsalve"
	ns.L["Soul Siphon"] = "Seelenentzug"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "Tanz des Tückischen"
	ns.L["Demonic Knowledge"] = "Dämonisches Wissen"
	ns.L["Grimoire of Synergy"] = "Grimoire der Synergie"
	ns.L["Invocation"] = "Anrufung"
	ns.L["Portal of Summoning"] = "Portal der Beschwörung"
	ns.L["Shadow and Flame"] = "Schatten und Flamme"
	ns.L["Shadowflame"] = "Schattenflamme"
	ns.L["Soul Harvesting"] = "Seelenernte"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "Blutraserei"
	ns.L["Consumed by Rage"] = "Von Wut zerfressen"
	ns.L["Devastate"] = "Verwüsten"
	ns.L["Endless Rage"] = "Endlose Wut"
	ns.L["Flagellation"] = "Geißelung"
	ns.L["Frenzied Assault"] = "Rasender Angriff"
	ns.L["Furious Thunder"] = "Wütender Donner"
	ns.L["Quick Strike"] = "Rasanter Schlag"
	ns.L["Raging Blow"] = "Wütender Schlag"
	ns.L["Single-Minded Fury"] = "Zielstrebiger Furor"
	ns.L["Victory Rush"] = "Siegesrausch"
	ns.L["Warbringer"] = "Kriegstreiber"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "Blutwoge"
	ns.L["Commanding Shout"] = "Befehlsruf"
	ns.L["Enraged Regeneration"] = "Wütende Regeneration"
	ns.L["Focused Rage"] = "Fokussierte Wut"
	ns.L["Intervene"] = "Einschreiten"
	ns.L["Precise Timing"] = "Präzises Timing"
	ns.L["Rallying Cry"] = "Anspornender Schrei"

elseif ns.locale == "esES" or ns.locale == "esMX" then
	ns.L["AddOn Description"] = "Todas las runas SoD. (¡Y más!)"
	ns.L["Arcane"] = "Arcana"
	ns.L["Demonic"] = "Demoníaca"
	ns.L["Duty"] = "Deber"
	ns.L["Hide if learnt"] = "Ocultar si se aprendió la runa"
	ns.L["Map Pin"] = "Marcador de mapa"
	ns.L["Mjolnir"] = "Mjolnir"
	ns.L["Phase 1 Summary"] = "Resumen de la fase 1"
	ns.L["Phase 2 Summary"] = "Resumen de la fase 2"
	ns.L["Runes"] = "Runas"
	ns.L["Skill Book"] = "Libro de habilidades"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "Furia de Tempestira"
	ns.L["Lacerate"] = "Lacerar"
	ns.L["Lifebloom"] = "Flor de vida"
	ns.L["Living Seed"] = "Semilla viviente"
	ns.L["Mangle"] = "Destrozar"
	ns.L["Savage Roar"] = "Rugido salvaje"
	ns.L["Skull Bash"] = "Testarazo"
	ns.L["Starsurge"] = "Oleada de estrellas"
	ns.L["Sunfire"] = "Fuego solar"
	ns.L["Survival of the Fittest"] = "Supervivencia del más fuerte"
	ns.L["Wild Growth"] = "Crecimiento salvaje"
	ns.L["Wild Strikes"] = "Golpes descontrolados"
	-- Druid Phase 2
	ns.L["Berserk"] = "Rabia"
	ns.L["Deeper Wilds"] = "El corazón de lo salvaje"
	ns.L["Dreamstate"] = "Estado onírico"
	ns.L["Eclipse"] = "Eclipse"
	ns.L["Enhanced Restoration"] = "Restauración mejorada"
	ns.L["King of the Jungle"] = "Rey de la selva"
	ns.L["Nourish"] = "Nutrir"
	ns.L["Revive"] = "Revivir"
	ns.L["Survival Instincts"] = "Instintos de supervivencia"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "Maestría en bestias"
	ns.L["Carve"] = "Trinchar"
	ns.L["Chimera Shot"] = "Disparo de quimera"
	ns.L["Cobra Strikes"] = "Golpes de cobra"
	ns.L["Explosive Shot"] = "Disparo explosivo"
	ns.L["Flanking Strike"] = "Golpe de flanco"
	ns.L["Heart of the Lion"] = "Corazón del león"
	ns.L["Kill Command"] = "Matar"
	ns.L["Lone Wolf"] = "Lobo solitario"
	ns.L["Master Marksman"] = "Maestro tirador"
	ns.L["Serpent Spread"] = "Propagar serpientes"
	ns.L["Sniper Training"] = "Instrucción de francotirador"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "Aspecto de la víbora"
	ns.L["Dual Wield Specialization"] = "Especialización en doble empuñadura"
	ns.L["Expose Weakness"] = "Exponer debilidad"
	ns.L["Invigoration"] = "Vigorización"
	ns.L["Melee Specialist"] = "Especialista cuerpo a cuerpo"
	ns.L["Steady Shot"] = "Disparo firme"
	ns.L["Trap Launcher"] = "Lanzador de trampas"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "Explosión Arcana"
	ns.L["Arcane Surge"] = "Oleada Arcana"
	ns.L["Burnout"] = "Consunción"
	ns.L["Enlightenment"] = "Esclarecimiento"
	ns.L["Fingers of Frost"] = "Dedos de Escarcha"
	ns.L["Ice Lance"] = "Lanza de hielo"
	ns.L["Icy Veins"] = "Venas heladas"
	ns.L["Living Bomb"] = "Bomba viva"
	ns.L["Living Flame"] = "Llama viva"
	ns.L["Mass Regeneration"] = "Regeneración en masa"
	ns.L["Regeneration"] = "Regeneración"
	ns.L["Rewind Time"] = "Retroceder en el tiempo"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "Congelación cerebral"
	ns.L["Chronostatic Preservation"] = "Preservación cronostática"
	ns.L["Expanded Intellect"] = "Intelecto ampliado"
	ns.L["Frostfire Bolt"] = "Descarga de Pirofrío"
	ns.L["Hot Streak"] = "Buena racha"
	ns.L["Missile Barrage"] = "Tromba de misiles"
	ns.L["Spell Power"] = "Poder con hechizos"
	ns.L["Spellfrost Bolt"] = "Descarga de Fríoarcano"
	-- Paladin Phase 1
	ns.L["Aegis"] = "Égida"
	ns.L["Avenger's Shield"] = "Escudo de vengador"
	ns.L["Beacon of Light"] = "Señal de la Luz"
	ns.L["Crusader Strike"] = "Golpe de cruzado"
	ns.L["Exorcist"] = "Exorcista"
	ns.L["Divine Sacrifice"] = "Sacrificio divino"
	ns.L["Divine Storm"] = "Tormenta divina"
	ns.L["Hand of Reckoning"] = "Mano de expiación"
	ns.L["Horn of Lordaeron"] = "Cuerno de Lordaeron"
	ns.L["Inspiration Exemplar"] = "Inspiración ejemplar"
	ns.L["Rebuke"] = "Reprimenda"
	ns.L["Seal of Martyrdom"] = "Sello de martirio"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "Bendiciones mejoradas"
	ns.L["Enlightened Judgements"] = "Sentencias iluminadas"
	ns.L["Guarded by the Light"] = "Custodiado por la Luz"
	ns.L["Infusion of Light"] = "Infusión de Luz"
	ns.L["Sacred Shield"] = "Escudo sacro"
	ns.L["Sheath of Light"] = "Vaina de Luz"
	ns.L["The Art of War"] = "El arte de la guerra"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "Círculo de sanación"
	ns.L["Homunculi"] = "Homúnculos"
	ns.L["Mind Sear"] = "Abrasamiento mental"
	ns.L["Penance"] = "Penitencia"
	ns.L["Power Word: Barrier"] = "Palabra de poder: barrera"
	ns.L["Prayer of Mending"] = "Rezo de alivio"
	ns.L["Serendipity"] = "Serendipia"
	ns.L["Shadow Word: Death"] = "Palabra de las Sombras: muerte"
	ns.L["Shared Pain"] = "Dolor compartido"
	ns.L["Strength of Soul"] = "Fuerza del alma"
	ns.L["Twisted Faith"] = "Fe retorcida"
	ns.L["Void Plague"] = "Plaga del Vacío"
	-- Priest Phase 2
	ns.L["Dispersion"] = "Dispersión"
	ns.L["Empowered Renew"] = "Renovar potenciado"
	ns.L["Increased Fortitude"] = "Entereza aumentada"
	ns.L["Mind Spike"] = "Púa mental"
	ns.L["Pain Suppression"] = "Supresión de dolor"
	ns.L["Renewed Hope"] = "Esperanza renovada"
	ns.L["Shadowfiend"] = "Maligno de las Sombras"
	ns.L["Spirit of the Redeemer"] = "Espíritu del redentor"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "Entre ceja y ceja"
	ns.L["Blade Dance"] = "Danza de hojas"
	ns.L["Deadly Brew"] = "Brebaje letal"
	ns.L["Envenom"] = "Envenenar"
	ns.L["Just a Flesh Wound"] = "Una simple herida superficial"
	ns.L["Main Gauche"] = "Daga de guardamano"
	ns.L["Mutilate"] = "Mutilar"
	ns.L["Quick Draw"] = "Desenvainado rápido"
	ns.L["Saber Slash"] = "Tajo de sable"
	ns.L["Shadowstrike"] = "Tenebrosa"
	ns.L["Slaughter from the Shadows"] = "Matanza desde las Sombras"
	ns.L["Shiv"] = "Puyazo"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "Maestro de la sutileza"
	ns.L["Poisoned Knife"] = "Cuchillo envenenado"
	ns.L["Redirect"] = "Redirigir"
	ns.L["Rolling with the Punches"] = "Improvisación defensiva"
	ns.L["Shadowstep"] = "Paso de las Sombras"
	ns.L["Shuriken Toss"] = "Lanzamiento de shuriken"
	ns.L["Waylay"] = "Artimaña"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "Guía ancestral"
	ns.L["Dual Wield Specialization"] = "Especialización en doble empuñadura"
	ns.L["Earth Shield"] = "Escudo de tierra"
	ns.L["Healing Rain"] = "Lluvia de sanación"
	ns.L["Lava Burst"] = "Ráfaga de lava"
	ns.L["Lava Lash"] = "Latigazo de lava"
	ns.L["Molten Blast"] = "Explosión de arrabio"
	ns.L["Overload"] = "Sobrecarga"
	ns.L["Shamanistic Rage"] = "Ira del chamán"
	ns.L["Shield Mastery"] = "Maestría con escudos"
	ns.L["Way of Earth"] = "Camino de la tierra"
	ns.L["Water Shield"] = "Escudo de agua"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "Despertar ancestral"
	ns.L["Decoy Totem"] = "Tótem señuelo"
	ns.L["Fire Nova"] = "Nova de Fuego"
	ns.L["Maelstrom Weapon"] = "Arma vorágine"
	ns.L["Power Surge"] = "Oleada de poder"
	ns.L["Spirit of the Alpha"] = "Espíritu del alfa"
	ns.L["Totemic Projection"] = "Proyección totémica"
	ns.L["Two-Handed Mastery"] = "Maestría con arma a dos manos"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "Descarga de caos"
	ns.L["Demonic Grace"] = "Gracia demoníaca"
	ns.L["Demonic Pact"] = "Pacto demoníaco"
	ns.L["Demonic Tactics"] = "Tácticas demoníacas"
	ns.L["Everlasting Affliction"] = "Aflicción eterna"
	ns.L["Haunt"] = "Poseer"
	ns.L["Incinerate"] = "Incinerar"
	ns.L["Lake of Fire"] = "Lago de Fuego"
	ns.L["Master Channeler"] = "Maestro canalizador"
	ns.L["Metamorphosis"] = "Metamorfosis"
	ns.L["Shadow Bolt Volley"] = "Salva de descarga de las Sombras"
	ns.L["Soul Siphon"] = "Succión de alma"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "Danza de los malditos"
	ns.L["Demonic Knowledge"] = "Conocimiento demoníaco"
	ns.L["Grimoire of Synergy"] = "Grimorio de sinergia"
	ns.L["Invocation"] = "Invocación"
	ns.L["Portal of Summoning"] = "Portal de invocación"
	ns.L["Shadow and Flame"] = "Sombras y llamas"
	ns.L["Shadowflame"] = "Pirosombra"
	ns.L["Soul Harvesting"] = "Cosecha de almas"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "Frenesí sangriento"
	ns.L["Consumed by Rage"] = "Consumido por la ira"
	ns.L["Devastate"] = "Devastar"
	ns.L["Endless Rage"] = "Ira interminable"
	ns.L["Flagellation"] = "Flagelación"
	ns.L["Frenzied Assault"] = "Asalto frenético"
	ns.L["Furious Thunder"] = "Trueno de furia"
	ns.L["Quick Strike"] = "Golpe rápido"
	ns.L["Raging Blow"] = "Arremetida enfurecida"
	ns.L["Single-Minded Fury"] = "Furia enfocada"
	ns.L["Victory Rush"] = "Ataque de la victoria"
	ns.L["Warbringer"] = "Belisario"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "Oleada sangrienta"
	ns.L["Commanding Shout"] = "Grito de orden"
	ns.L["Enraged Regeneration"] = "Regeneración iracunda"
	ns.L["Focused Rage"] = "Ira enfocada"
	ns.L["Intervene"] = "Intervenir"
	ns.L["Precise Timing"] = "Sincronización precisa"
	ns.L["Rallying Cry"] = "Berrido de convocación"

elseif ns.locale == "frFR" then
	ns.L["AddOn Description"] = "Toutes les runes SoD. (Et plus!)"
	ns.L["Arcane"] = "Arcanes"
	ns.L["Demonic"] = "Démoniaque"
	ns.L["Duty"] = "Devoir"
	ns.L["Hide if learnt"] = "Cacher si la rune a été apprise"
	ns.L["Map Pin"] = "Broche de carte"
	ns.L["Mjolnir"] = "Mjolnir"
	ns.L["Phase 1 Summary"] = "Résumé de la phase 1"
	ns.L["Phase 2 Summary"] = "Résumé de la phase 2"
	ns.L["Runes"] = "Runes"
	ns.L["Skill Book"] = "Livre de compétences"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "Fureur de Hurlorage"
	ns.L["Lacerate"] = "Lacérer"
	ns.L["Lifebloom"] = "Fleur de vie"
	ns.L["Living Seed"] = "Graine de vie"
	ns.L["Mangle"] = "Mutilation"
	ns.L["Savage Roar"] = "Rugissement sauvage"
	ns.L["Skull Bash"] = "Coup de crâne"
	ns.L["Starsurge"] = "Éruption stellaire"
	ns.L["Sunfire"] = "Éclat solaire"
	ns.L["Survival of the Fittest"] = "Survie du plus fort"
	ns.L["Wild Growth"] = "Croissance sauvage"
	ns.L["Wild Strikes"] = "Frappes féroces"
	-- Druid Phase 2
	ns.L["Berserk"] = "Berserk"
	ns.L["Deeper Wilds"] = "Fauverie accentuée"
	ns.L["Dreamstate"] = "État de rêve"
	ns.L["Eclipse"] = "Éclipse"
	ns.L["Enhanced Restoration"] = "Restauration amplifiée"
	ns.L["King of the Jungle"] = "Roi de la jungle"
	ns.L["Nourish"] = "Nourrir"
	ns.L["Revive"] = "Ressusciter"
	ns.L["Survival Instincts"] = "Instincts de survie"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "Maîtrise des bêtes"
	ns.L["Carve"] = "Écharper"
	ns.L["Chimera Shot"] = "Tir de la chimère"
	ns.L["Cobra Strikes"] = "Frappes de cobra"
	ns.L["Explosive Shot"] = "Tir explosif"
	ns.L["Flanking Strike"] = "Frappe latérale"
	ns.L["Heart of the Lion"] = "Cœur de lion"
	ns.L["Kill Command"] = "Ordre de tuer"
	ns.L["Lone Wolf"] = "Loup solitaire"
	ns.L["Master Marksman"] = "Maître tireur"
	ns.L["Serpent Spread"] = "Propagation du serpent"
	ns.L["Sniper Training"] = "Entraînement de sniper"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "Aspect de la vipère"
	ns.L["Dual Wield Specialization"] = "Spécialisation Ambidextrie"
	ns.L["Expose Weakness"] = "Perce-faille"
	ns.L["Invigoration"] = "Revigoration"
	ns.L["Melee Specialist"] = "Spécialiste de la mêlée"
	ns.L["Steady Shot"] = "Tir assuré"
	ns.L["Trap Launcher"] = "Lance-piège"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "Déflagration des arcanes"
	ns.L["Arcane Surge"] = "Éruption d’arcanes"
	ns.L["Burnout"] = "Ardeur épuisante"
	ns.L["Enlightenment"] = "Illumination"
	ns.L["Fingers of Frost"] = "Doigts de givre"
	ns.L["Ice Lance"] = "Javelot de glace"
	ns.L["Icy Veins"] = "Veines glaciales"
	ns.L["Living Bomb"] = "Bombe vivante"
	ns.L["Living Flame"] = "Flamme vivante"
	ns.L["Mass Regeneration"] = "Régénération de masse"
	ns.L["Regeneration"] = "Régénération"
	ns.L["Rewind Time"] = "Remonter le temps"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "Gel mental"
	ns.L["Chronostatic Preservation"] = "Préservation chronostatique"
	ns.L["Expanded Intellect"] = "Intelligence étendue"
	ns.L["Frostfire Bolt"] = "Éclair de givrefeu"
	ns.L["Hot Streak"] = "Bonne série"
	ns.L["Missile Barrage"] = "Barrage de projectiles"
	ns.L["Spell Power"] = "Puissance des sorts"
	ns.L["Spellfrost Bolt"] = "Descarga de Fríoarcano"
	-- Paladin Phase 1
	ns.L["Aegis"] = "Egide"
	ns.L["Avenger's Shield"] = "Bouclier du vengeur"
	ns.L["Beacon of Light"] = "Guide de lumière"
	ns.L["Crusader Strike"] = "Frappe du croisé"
	ns.L["Exorcist"] = "Exorciste"
	ns.L["Divine Sacrifice"] = "Sacrifice divin"
	ns.L["Divine Storm"] = "Tempête divine"
	ns.L["Hand of Reckoning"] = "Main de rétribution"
	ns.L["Horn of Lordaeron"] = "Cor de Lordaeron"
	ns.L["Inspiration Exemplar"] = "Source d’inspiration"
	ns.L["Rebuke"] = "Réprimandes"
	ns.L["Seal of Martyrdom"] = "Sceau du martyr"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "Bénédictions amplifiées"
	ns.L["Enlightened Judgements"] = "Jugements éclairés"
	ns.L["Guarded by the Light"] = "Gardé par la Lumière"
	ns.L["Infusion of Light"] = "Imprégnation de lumière"
	ns.L["Sacred Shield"] = "Bouclier saint"
	ns.L["Sheath of Light"] = "Fourreau de lumière"
	ns.L["The Art of War"] = "L’art de la guerre"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "Cercle de soins"
	ns.L["Homunculi"] = "Homoncules"
	ns.L["Mind Sear"] = "Incandescence mentale"
	ns.L["Penance"] = "Pénitence"
	ns.L["Power Word: Barrier"] = "Mot de pouvoir : Barrière"
	ns.L["Prayer of Mending"] = "Prière de guérison"
	ns.L["Serendipity"] = "Heureux hasard"
	ns.L["Shadow Word: Death"] = "Mot de l’ombre : Mort"
	ns.L["Shared Pain"] = "Souffrance partagée"
	ns.L["Strength of Soul"] = "Force d’âme"
	ns.L["Twisted Faith"] = "Foi distordue"
	ns.L["Void Plague"] = "Fléau du Vide"
	-- Priest Phase 2
	ns.L["Dispersion"] = "Dispersion"
	ns.L["Empowered Renew"] = "Rénovation surpuissante"
	ns.L["Increased Fortitude"] = "Robustesse augmentée"
	ns.L["Mind Spike"] = "Pointe mentale"
	ns.L["Pain Suppression"] = "Suppression de la douleur"
	ns.L["Renewed Hope"] = "Regain d’espoir"
	ns.L["Shadowfiend"] = "Ombrefiel"
	ns.L["Spirit of the Redeemer"] = "Esprit du rédempteur"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "Entre les deux yeux"
	ns.L["Blade Dance"] = "Danse des lames"
	ns.L["Deadly Brew"] = "Breuvage mortel"
	ns.L["Envenom"] = "Envenimer"
	ns.L["Just a Flesh Wound"] = "Juste une égratignure"
	ns.L["Main Gauche"] = "Main gauche"
	ns.L["Mutilate"] = "Estropier"
	ns.L["Quick Draw"] = "Tireur rapide"
	ns.L["Saber Slash"] = "Coup de sabre"
	ns.L["Shadowstrike"] = "Frappe-ténèbres"
	ns.L["Slaughter from the Shadows"] = "Ombres meurtrières"
	ns.L["Shiv"] = "Kriss"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "Maître de la discrétion"
	ns.L["Poisoned Knife"] = "Couteau empoisonné"
	ns.L["Redirect"] = "Redirection"
	ns.L["Rolling with the Punches"] = "Encaisser les coups"
	ns.L["Shadowstep"] = "Pas de l’ombre"
	ns.L["Shuriken Toss"] = "Lancer de shuriken"
	ns.L["Waylay"] = "Affût"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "Soutien ancestral"
	ns.L["Dual Wield Specialization"] = "Spécialisation Ambidextrie"
	ns.L["Earth Shield"] = "Bouclier de terre"
	ns.L["Healing Rain"] = "Pluie guérisseuse"
	ns.L["Lava Burst"] = "Explosion de lave"
	ns.L["Lava Lash"] = "Latigazo de lava"
	ns.L["Molten Blast"] = "Éclair de lave"
	ns.L["Overload"] = "Surcharge"
	ns.L["Shamanistic Rage"] = "Rage du chaman"
	ns.L["Shield Mastery"] = "Maîtrise du bouclier"
	ns.L["Way of Earth"] = "Voie de la terre"
	ns.L["Water Shield"] = "Bouclier d’eau"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "Éveil ancestral"
	ns.L["Decoy Totem"] = "Totem de leurre"
	ns.L["Fire Nova"] = "Nova de feu"
	ns.L["Maelstrom Weapon"] = "Arme du Maelström"
	ns.L["Power Surge"] = "Vague de puissance"
	ns.L["Spirit of the Alpha"] = "Esprit de l’alpha"
	ns.L["Totemic Projection"] = "Projection totémique"
	ns.L["Two-Handed Mastery"] = "Maîtrise à deux mains"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "Trait du chaos"
	ns.L["Demonic Grace"] = "Grâce démoniaque"
	ns.L["Demonic Pact"] = "Pacte démoniaque"
	ns.L["Demonic Tactics"] = "Tactique démoniaque"
	ns.L["Everlasting Affliction"] = "Affliction éternelle"
	ns.L["Haunt"] = "Hanter"
	ns.L["Incinerate"] = "Incinérer"
	ns.L["Lake of Fire"] = "Lac de feu"
	ns.L["Master Channeler"] = "Maîtrise de la canalisation"
	ns.L["Metamorphosis"] = "Métamorphose"
	ns.L["Shadow Bolt Volley"] = "Salve de Traits de l’ombre"
	ns.L["Soul Siphon"] = "Siphon d’âme"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "Danse des malveillants"
	ns.L["Demonic Knowledge"] = "Connaissance démoniaque"
	ns.L["Grimoire of Synergy"] = "Grimoire de synergie"
	ns.L["Invocation"] = "Évocation"
	ns.L["Portal of Summoning"] = "Portail d’invocation"
	ns.L["Shadow and Flame"] = "Ombre et flammes"
	ns.L["Shadowflame"] = "Ombreflamme"
	ns.L["Soul Harvesting"] = "Moisson d’âme"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "Frénésie sanglante"
	ns.L["Consumed by Rage"] = "Consumé par la rage"
	ns.L["Devastate"] = "Dévaster"
	ns.L["Endless Rage"] = "Rage infinie"
	ns.L["Flagellation"] = "Flagellation"
	ns.L["Frenzied Assault"] = "Assaut frénétique"
	ns.L["Furious Thunder"] = "Tonnerre furieux"
	ns.L["Quick Strike"] = "Frappe rapide"
	ns.L["Raging Blow"] = "Coup déchaîné"
	ns.L["Single-Minded Fury"] = "Fureur obsessionnelle"
	ns.L["Victory Rush"] = "Ivresse de la victoire"
	ns.L["Warbringer"] = "Porteguerre"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "Vague de sang"
	ns.L["Commanding Shout"] = "Cri de commandement"
	ns.L["Enraged Regeneration"] = "Régénération enragée"
	ns.L["Focused Rage"] = "Rage focalisée"
	ns.L["Intervene"] = "Intervention"
	ns.L["Precise Timing"] = "Moment exact"
	ns.L["Rallying Cry"] = "Cri de ralliement"

elseif ns.locale == "koKR" then
	ns.L["AddOn Description"] = "모든 SoD 룬. (그리고 더!)."
	ns.L["Arcane"] = "비전"
	ns.L["Demonic"] = "악마의"
	ns.L["Duty"] = "의무"
	ns.L["Hide if learnt"] = "룬을 배웠다면 숨기기"
	ns.L["Map Pin"] = "지도 핀"
	ns.L["Mjolnir"] = "묠니르"
	ns.L["Phase 1 Summary"] = "1단계 요약"
	ns.L["Phase 2 Summary"] = "2단계 요약"
	ns.L["Runes"] = "룬"
	ns.L["Skill Book"] = "스킬북"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "스톰레이지의 격노"
	ns.L["Lacerate"] = "가르기"
	ns.L["Lifebloom"] = "피어나는 생명"
	ns.L["Living Seed"] = "살아있는 씨앗"
	ns.L["Mangle"] = "짓이기기"
	ns.L["Savage Roar"] = "야생의 포효"
	ns.L["Skull Bash"] = "두개골 강타"
	ns.L["Starsurge"] = "별빛쇄도"
	ns.L["Sunfire"] = "태양섬광"
	ns.L["Survival of the Fittest"] = "적자 생존"
	ns.L["Wild Growth"] = "급속 성장"
	ns.L["Wild Strikes"] = "야생의 강타"
	-- Druid Phase 2
	ns.L["Berserk"] = "광폭화"
	ns.L["Deeper Wilds"] = "깊은 야생"
	ns.L["Dreamstate"] = "꿈결"
	ns.L["Eclipse"] = "일월식"
	ns.L["Enhanced Restoration"] = "강화된 회복"
	ns.L["King of the Jungle"] = "정글의 왕"
	ns.L["Nourish"] = "육성"
	ns.L["Revive"] = "되살리기"
	ns.L["Survival Instincts"] = "생존 본능"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "야수 숙련"
	ns.L["Carve"] = "저미기"
	ns.L["Chimera Shot"] = "키메라 사격"
	ns.L["Cobra Strikes"] = "코브라의 일격"
	ns.L["Explosive Shot"] = "폭발 사격"
	ns.L["Flanking Strike"] = "측방 강타"
	ns.L["Heart of the Lion"] = "사자의 심장"
	ns.L["Kill Command"] = "살상 명령"
	ns.L["Lone Wolf"] = "고독한 늑대"
	ns.L["Master Marksman"] = "사격의 명수"
	ns.L["Serpent Spread"] = "독사 확산"
	ns.L["Sniper Training"] = "저격 훈련"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "독사의 상"
	ns.L["Dual Wield Specialization"] = "쌍수 무기 전문화"
	ns.L["Expose Weakness"] = "결점 노출"
	ns.L["Invigoration"] = "사기 고취"
	ns.L["Melee Specialist"] = "근접 전투 전문가"
	ns.L["Steady Shot"] = "고정 사격"
	ns.L["Trap Launcher"] = "덫 발사"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "비전 작렬"
	ns.L["Arcane Surge"] = "비전 쇄도"
	ns.L["Burnout"] = "완전 연소"
	ns.L["Enlightenment"] = "깨달음"
	ns.L["Fingers of Frost"] = "서리의 손가락"
	ns.L["Ice Lance"] = "얼음창"
	ns.L["Icy Veins"] = "얼음 핏줄"
	ns.L["Living Bomb"] = "살아있는 폭탄"
	ns.L["Living Flame"] = "살아있는 불꽃"
	ns.L["Mass Regeneration"] = "대규모 재생력"
	ns.L["Regeneration"] = "재생"
	ns.L["Rewind Time"] = "시간 되돌리기"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "두뇌 빙결"
	ns.L["Chronostatic Preservation"] = "시간의 보존"
	ns.L["Expanded Intellect"] = "확장된 지능"
	ns.L["Frostfire Bolt"] = "얼음불꽃 화살"
	ns.L["Hot Streak"] = "몰아치는 열기"
	ns.L["Missile Barrage"] = "화살 탄막"
	ns.L["Spell Power"] = "주문 강화"
	ns.L["Spellfrost Bolt"] = "비전냉기 화살"
	-- Paladin Phase 1
	ns.L["Aegis"] = "보호"
	ns.L["Avenger's Shield"] = "응징의 방패"
	ns.L["Beacon of Light"] = "빛의 봉화"
	ns.L["Crusader Strike"] = "성전사의 일격"
	ns.L["Exorcist"] = "퇴마사"
	ns.L["Divine Sacrifice"] = "성스러운 희생"
	ns.L["Divine Storm"] = "천상의 폭풍"
	ns.L["Hand of Reckoning"] = "심판의 손길"
	ns.L["Horn of Lordaeron"] = "로데론의 뿔피리"
	ns.L["Inspiration Exemplar"] = "영감의 모범"
	ns.L["Rebuke"] = "비난"
	ns.L["Seal of Martyrdom"] = "헌신의 문장"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "강화된 축복"
	ns.L["Enlightened Judgements"] = "깨달음의 심판"
	ns.L["Guarded by the Light"] = "빛의 인도"
	ns.L["Infusion of Light"] = "빛 주입"
	ns.L["Sacred Shield"] = "성스러운 보호막"
	ns.L["Sheath of Light"] = "수호의 빛"
	ns.L["The Art of War"] = "전쟁의 기술"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "치유의 마법진"
	ns.L["Homunculi"] = "호문쿨루스"
	ns.L["Mind Sear"] = "정신 불태우기"
	ns.L["Penance"] = "회개"
	ns.L["Power Word: Barrier"] = "신의 권능: 방벽"
	ns.L["Prayer of Mending"] = "회복의 기원"
	ns.L["Serendipity"] = "우연한 행운"
	ns.L["Shadow Word: Death"] = "어둠의 권능: 죽음"
	ns.L["Shared Pain"] = "나누는 고통"
	ns.L["Strength of Soul"] = "굳건한 정신"
	ns.L["Twisted Faith"] = "뒤틀린 믿음"
	ns.L["Void Plague"] = "공허의 역병"
	-- Priest Phase 2
	ns.L["Dispersion"] = "분산"
	ns.L["Empowered Renew"] = "소생 강화"
	ns.L["Increased Fortitude"] = "증가한 인내"
	ns.L["Mind Spike"] = "정신의 쐐기"
	ns.L["Pain Suppression"] = "고통 억제"
	ns.L["Renewed Hope"] = "새로운 희망"
	ns.L["Shadowfiend"] = "어둠의 마귀"
	ns.L["Spirit of the Redeemer"] = "구원자의 영혼"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "미간 적중"
	ns.L["Blade Dance"] = "칼춤"
	ns.L["Deadly Brew"] = "맹독 조합"
	ns.L["Envenom"] = "독살"
	ns.L["Just a Flesh Wound"] = "얕은 상처일 뿐"
	ns.L["Main Gauche"] = "맹고쉬"
	ns.L["Mutilate"] = "절단"
	ns.L["Quick Draw"] = "빠른 사격"
	ns.L["Saber Slash"] = "사브르 베기"
	ns.L["Shadowstrike"] = "그림자 일격"
	ns.L["Slaughter from the Shadows"] = "어둠의 학살자"
	ns.L["Shiv"] = "독칼"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "잠행의 대가"
	ns.L["Poisoned Knife"] = "독 칼"
	ns.L["Redirect"] = "되돌리기"
	ns.L["Rolling with the Punches"] = "충격 완화"
	ns.L["Shadowstep"] = "그림자 밟기"
	ns.L["Shuriken Toss"] = "표창 투척"
	ns.L["Waylay"] = "습격"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "고대의 인도"
	ns.L["Dual Wield Specialization"] = "쌍수 무기 전문화"
	ns.L["Earth Shield"] = "대지의 보호막"
	ns.L["Healing Rain"] = "치유의 비"
	ns.L["Lava Burst"] = "용암 폭발"
	ns.L["Lava Lash"] = "용암 채찍"
	ns.L["Molten Blast"] = "용암 작열"
	ns.L["Overload"] = "과부하"
	ns.L["Shamanistic Rage"] = "주술의 분노"
	ns.L["Shield Mastery"] = "방패 숙련"
	ns.L["Way of Earth"] = "대지의 길"
	ns.L["Water Shield"] = "물의 보호막"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "고대의 각성"
	ns.L["Decoy Totem"] = "미끼 토템"
	ns.L["Fire Nova"] = "불꽃 회오리"
	ns.L["Maelstrom Weapon"] = "소용돌이치는 무기"
	ns.L["Power Surge"] = "마력의 쇄도"
	ns.L["Spirit of the Alpha"] = "우두머리의 영혼"
	ns.L["Totemic Projection"] = "토템 재배치"
	ns.L["Two-Handed Mastery"] = "양손 장비 숙련"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "혼돈의 화살"
	ns.L["Demonic Grace"] = "악마의 은총"
	ns.L["Demonic Pact"] = "악마의 서약"
	ns.L["Demonic Tactics"] = "악마의 술책"
	ns.L["Everlasting Affliction"] = "영원한 고통"
	ns.L["Haunt"] = "유령 출몰"
	ns.L["Incinerate"] = "소각"
	ns.L["Lake of Fire"] = "불꽃의 호수"
	ns.L["Master Channeler"] = "역술의 대가"
	ns.L["Metamorphosis"] = "탈태"
	ns.L["Shadow Bolt Volley"] = "연발 어둠의 화살"
	ns.L["Soul Siphon"] = "영혼 착취"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "악인의 춤"
	ns.L["Demonic Knowledge"] = "악마의 지식"
	ns.L["Grimoire of Synergy"] = "흑마법서: 결속"
	ns.L["Invocation"] = "환기"
	ns.L["Portal of Summoning"] = "소환의 차원문"
	ns.L["Shadow and Flame"] = "어둠과 불길"
	ns.L["Shadowflame"] = "암흑불길"
	ns.L["Soul Harvesting"] = "영혼 수확"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "피의 광란"
	ns.L["Consumed by Rage"] = "분노 잠식"
	ns.L["Devastate"] = "압도"
	ns.L["Endless Rage"] = "끝없는 분노"
	ns.L["Flagellation"] = "채찍질"
	ns.L["Frenzied Assault"] = "광란의 공격"
	ns.L["Furious Thunder"] = "격노의 천둥"
	ns.L["Quick Strike"] = "속전속결"
	ns.L["Raging Blow"] = "분노의 강타"
	ns.L["Single-Minded Fury"] = "하나된 분노"
	ns.L["Victory Rush"] = "승리의 돌진"
	ns.L["Warbringer"] = "돌격대장"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "피 분출"
	ns.L["Commanding Shout"] = "지휘의 외침"
	ns.L["Enraged Regeneration"] = "분노의 재생력"
	ns.L["Focused Rage"] = "분노 집중"
	ns.L["Intervene"] = "가로막기"
	ns.L["Precise Timing"] = "정확한 시간 감각"
	ns.L["Rallying Cry"] = "재집결의 함성"

elseif ns.locale == "ptBR" or ns.locale == "ptPT" then
	ns.L["AddOn Description"] = "Todas as runas SoD. (E mais!)"
	ns.L["Arcane"] = "Arcana"
	ns.L["Demonic"] = "Demoníaca"
	ns.L["Duty"] = "Dever"
	ns.L["Hide if learnt"] = "Esconda-se se a runa foi aprendida"
	ns.L["Map Pin"] = "Pino do mapa:"
	ns.L["Mjolnir"] = "Mjolnir"
	ns.L["Phase 1 Summary"] = "Resumo da Fase 1"
	ns.L["Phase 2 Summary"] = "Resumo da Fase 2"
	ns.L["Runes"] = "Runas"
	ns.L["Skill Book"] = "Livro de habilidades"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "Fúria de Tempesfúria"
	ns.L["Lacerate"] = "Lacerar"
	ns.L["Lifebloom"] = "Brotar da Vida"
	ns.L["Living Seed"] = "Semente Viva"
	ns.L["Mangle"] = "Destroçar"
	ns.L["Savage Roar"] = "Rugido Selvagem"
	ns.L["Skull Bash"] = "Esmagar Crânio"
	ns.L["Starsurge"] = "Surto Estelar"
	ns.L["Sunfire"] = "Fogo Solar"
	ns.L["Survival of the Fittest"] = "A Lei da Selva"
	ns.L["Wild Growth"] = "Crescimento Silvestre"
	ns.L["Wild Strikes"] = "Golpes Selvagens"
	-- Druid Phase 2
	ns.L["Berserk"] = "Berserk"
	ns.L["Deeper Wilds"] = "Indomabilidade Profunda"
	ns.L["Dreamstate"] = "Estado Onírico"
	ns.L["Eclipse"] = "Eclipse"
	ns.L["Enhanced Restoration"] = "Restauração Aprimorada"
	ns.L["King of the Jungle"] = "Rei da Selva"
	ns.L["Nourish"] = "Nutrir"
	ns.L["Revive"] = "Reviver"
	ns.L["Survival Instincts"] = "Instintos de Sobrevivência"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "Domínio das Feras"
	ns.L["Carve"] = "Trinchar"
	ns.L["Chimera Shot"] = "Tiro Quimérico"
	ns.L["Cobra Strikes"] = "Golpes de Naja"
	ns.L["Explosive Shot"] = "Tiro Explosivo"
	ns.L["Flanking Strike"] = "Ataque Flanqueante"
	ns.L["Heart of the Lion"] = "Coração de Leão"
	ns.L["Kill Command"] = "Comando para Matar"
	ns.L["Lone Wolf"] = "Lobo Solitário"
	ns.L["Master Marksman"] = "Mestre Atirador Perito"
	ns.L["Serpent Spread"] = "Espalhar de Serpente"
	ns.L["Sniper Training"] = "Treinamento de Franco-atirador"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "Aspecto da Víbora"
	ns.L["Dual Wield Specialization"] = "Especialização em Duas Armas"
	ns.L["Expose Weakness"] = "Expor Fraqueza"
	ns.L["Invigoration"] = "Envigorar"
	ns.L["Melee Specialist"] = "Especialista em Corpo a Corpo"
	ns.L["Steady Shot"] = "Tiro Firme"
	ns.L["Trap Launcher"] = "Lançador de Armadilhas"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "Impacto Arcano"
	ns.L["Arcane Surge"] = "Surto Arcano"
	ns.L["Burnout"] = "Combustão"
	ns.L["Enlightenment"] = "Esclarecimento"
	ns.L["Fingers of Frost"] = "Dedos Glaciais"
	ns.L["Ice Lance"] = "Lança de Gelo"
	ns.L["Icy Veins"] = "Veias Gélidas"
	ns.L["Living Bomb"] = "Bomba Viva"
	ns.L["Living Flame"] = "Chama Viva"
	ns.L["Mass Regeneration"] = "Regeneração em Massa"
	ns.L["Regeneration"] = "Regeneração"
	ns.L["Rewind Time"] = "Retroceder Tempo"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "Congelamento Cerebral"
	ns.L["Chronostatic Preservation"] = "Preservação Cronostática"
	ns.L["Expanded Intellect"] = "Intelecto Expandido"
	ns.L["Frostfire Bolt"] = "Seta de Fogofrio"
	ns.L["Hot Streak"] = "Embalo de Fogo"
	ns.L["Missile Barrage"] = "Salva de Mísseis"
	ns.L["Spell Power"] = "Poder Mágico"
	ns.L["Spellfrost Bolt"] = "Seta de Gelo Mágico"
	-- Paladin Phase 1
	ns.L["Aegis"] = "Égide"
	ns.L["Avenger's Shield"] = "Escudo do Vingador"
	ns.L["Beacon of Light"] = "Foco de Luz"
	ns.L["Crusader Strike"] = "Golpe do Cruzado"
	ns.L["Exorcist"] = "Exorcista"
	ns.L["Divine Sacrifice"] = "Sacrifício Divino"
	ns.L["Divine Storm"] = "Tempestade Divina"
	ns.L["Hand of Reckoning"] = "Mão da Desforra"
	ns.L["Horn of Lordaeron"] = "Trompa de Lordaeron"
	ns.L["Inspiration Exemplar"] = "Modelo de Inspiração"
	ns.L["Rebuke"] = "Repreensão"
	ns.L["Seal of Martyrdom"] = "Selo do Martírio"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "Bênçãos Aprimoradas"
	ns.L["Enlightened Judgements"] = "Julgamentos Esclarecidos"
	ns.L["Guarded by the Light"] = "Protegido pela Luz"
	ns.L["Infusion of Light"] = "Infusão de Luz"
	ns.L["Sacred Shield"] = "Escudo Sagrado"
	ns.L["Sheath of Light"] = "Bainha de Luz"
	ns.L["The Art of War"] = "A Arte da Guerra"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "Círculo de Cura"
	ns.L["Homunculi"] = "Homúnculos"
	ns.L["Mind Sear"] = "Calcinação Mental"
	ns.L["Penance"] = "Penitência"
	ns.L["Power Word: Barrier"] = "Palavra de Poder: Barreira"
	ns.L["Prayer of Mending"] = "Prece da Recomposição"
	ns.L["Serendipity"] = "Serendipidade"
	ns.L["Shadow Word: Death"] = "Palavra Sombria: Morte"
	ns.L["Shared Pain"] = "Dor Compartilhada"
	ns.L["Strength of Soul"] = "Força da Alma"
	ns.L["Twisted Faith"] = "Fé Corrompida"
	ns.L["Void Plague"] = "Peste do Caos"
	-- Priest Phase 2
	ns.L["Dispersion"] = "Dispersão"
	ns.L["Empowered Renew"] = "Renovação Potencializada"
	ns.L["Increased Fortitude"] = "Fortitude Aumentada"
	ns.L["Mind Spike"] = "Aguilhão Mental"
	ns.L["Pain Suppression"] = "Supressão de Dor"
	ns.L["Renewed Hope"] = "Esperança Renovada"
	ns.L["Shadowfiend"] = "Demônio das Sombras"
	ns.L["Spirit of the Redeemer"] = "Espírito do Redentor"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "No Meio da Testa"
	ns.L["Blade Dance"] = "Dança de Lâminas"
	ns.L["Deadly Brew"] = "Mistura Mortífera"
	ns.L["Envenom"] = "Envenenar"
	ns.L["Just a Flesh Wound"] = "Só Um Arranhão"
	ns.L["Main Gauche"] = "Adaga de Bloqueio"
	ns.L["Mutilate"] = "Mutilar"
	ns.L["Quick Draw"] = "Saque Rápido"
	ns.L["Saber Slash"] = "Talho de Sabre"
	ns.L["Shadowstrike"] = "Golpe Sombrio"
	ns.L["Slaughter from the Shadows"] = "Atacar das Sombras"
	ns.L["Shiv"] = "Estocada"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "Mestre do Subterfúgio"
	ns.L["Poisoned Knife"] = "Faca Envenenada"
	ns.L["Redirect"] = "Redirecionar"
	ns.L["Rolling with the Punches"] = "Adaptar à Situação"
	ns.L["Shadowstep"] = "Passo Furtivo"
	ns.L["Shuriken Toss"] = "Lançar Shuriken"
	ns.L["Waylay"] = "Atocaiar"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "Conselho dos Ancestrais"
	ns.L["Dual Wield Specialization"] = "Especialização em Duas Armas"
	ns.L["Earth Shield"] = "Escudo da Terra"
	ns.L["Healing Rain"] = "Chuva Curativa"
	ns.L["Lava Burst"] = "Estouro de Lava"
	ns.L["Lava Lash"] = "Açoite de Lava"
	ns.L["Molten Blast"] = "Impacto Derretido"
	ns.L["Overload"] = "Sobrecarga"
	ns.L["Shamanistic Rage"] = "Fúria Xamanística"
	ns.L["Shield Mastery"] = "Proficiência em Escudo"
	ns.L["Way of Earth"] = "Caminho Telúrico"
	ns.L["Water Shield"] = "Escudo de Água"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "Despertar Ancestral"
	ns.L["Decoy Totem"] = "Totem Chamariz"
	ns.L["Fire Nova"] = "Nova de Fogo"
	ns.L["Maelstrom Weapon"] = "Arma da Voragem"
	ns.L["Power Surge"] = "Surto de Poder"
	ns.L["Spirit of the Alpha"] = "Espírito do Alfa"
	ns.L["Totemic Projection"] = "Projeção Totêmica"
	ns.L["Two-Handed Mastery"] = "Maestria em Duas Mãos"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "Seta do Caos"
	ns.L["Demonic Grace"] = "Graça Demoníaca"
	ns.L["Demonic Pact"] = "Pacto Demoníaco"
	ns.L["Demonic Tactics"] = "Táticas Demoníacas"
	ns.L["Everlasting Affliction"] = "Agonia Eterna"
	ns.L["Haunt"] = "Assombrar"
	ns.L["Incinerate"] = "Incinerar"
	ns.L["Lake of Fire"] = "Lago de Fogo"
	ns.L["Master Channeler"] = "Mestre Canalizador"
	ns.L["Metamorphosis"] = "Metamorfose"
	ns.L["Shadow Bolt Volley"] = "Salva de Setas Sombrias"
	ns.L["Soul Siphon"] = "Sifão da Alma"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "Dança dos Perversos"
	ns.L["Demonic Knowledge"] = "Conhecimento Demoníaco"
	ns.L["Grimoire of Synergy"] = "Grimório de Sinergia"
	ns.L["Invocation"] = "Invocação"
	ns.L["Portal of Summoning"] = "Portal de Evocação"
	ns.L["Shadow and Flame"] = "Sombra e Chama"
	ns.L["Shadowflame"] = "Chama Sombria"
	ns.L["Soul Harvesting"] = "Almas Colhidas"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "Frenesi de Sangue"
	ns.L["Consumed by Rage"] = "Consumido pela Raiva"
	ns.L["Devastate"] = "Devastar"
	ns.L["Endless Rage"] = "Raiva Infinita"
	ns.L["Flagellation"] = "Flagelação"
	ns.L["Frenzied Assault"] = "Ataque Frenético"
	ns.L["Furious Thunder"] = "Trovão Furioso"
	ns.L["Quick Strike"] = "Golpe Rápido"
	ns.L["Raging Blow"] = "Golpe Furioso"
	ns.L["Single-Minded Fury"] = "Fúria Obcecada"
	ns.L["Victory Rush"] = "Ímpeto da Vitória"
	ns.L["Warbringer"] = "Armipotente"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "Rebentação de Sangue"
	ns.L["Commanding Shout"] = "Brado de Comando"
	ns.L["Enraged Regeneration"] = "Regeneração Enfurecida"
	ns.L["Focused Rage"] = "Raiva Concentrada"
	ns.L["Intervene"] = "Comprar Briga"
	ns.L["Precise Timing"] = "Momento Exato"
	ns.L["Rallying Cry"] = "Brado de Convocação"

elseif ns.locale == "ruRU" then
	ns.L["AddOn Description"] = "Все руны SoD. (И более!)"
	ns.L["Arcane"] = "Чародейская"
	ns.L["Demonic"] = "Демоническая"
	ns.L["Duty"] = "долга"
	ns.L["Hide if learnt"] = "Скрыть, если руна была изучена"
	ns.L["Map Pin"] = "Карта Пин"
	ns.L["Mjolnir"] = "Мьольнира"
	ns.L["Phase 1 Summary"] = "Резюме этапа 1"
	ns.L["Phase 2 Summary"] = "Резюме этапа 2"
	ns.L["Runes"] = "Руны"
	ns.L["Skill Book"] = "Книга навыков"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "Гнев Ярости Бури"
	ns.L["Lacerate"] = "Растерзать"
	ns.L["Lifebloom"] = "Жизнецвет"
	ns.L["Living Seed"] = "Семя жизни"
	ns.L["Mangle"] = "Увечье"
	ns.L["Savage Roar"] = "Дикий рев"
	ns.L["Skull Bash"] = "Лобовая атака"
	ns.L["Starsurge"] = "Звездный поток"
	ns.L["Sunfire"] = "Солнечный огонь"
	ns.L["Survival of the Fittest"] = "Выживание сильнейших"
	ns.L["Wild Growth"] = "Буйный рост"
	ns.L["Wild Strikes"] = "Дикие удары"
	-- Druid Phase 2
	ns.L["Berserk"] = "Берсерк"
	ns.L["Deeper Wilds"] = "Глубокая чаща"
	ns.L["Dreamstate"] = "Состояние сна"
	ns.L["Eclipse"] = "Затмение"
	ns.L["Enhanced Restoration"] = "Усиленное восстановление"
	ns.L["King of the Jungle"] = "Король джунглей"
	ns.L["Nourish"] = "Покровительство природы"
	ns.L["Revive"] = "Оживление"
	ns.L["Survival Instincts"] = "Инстинкты выживания"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "Повелитель зверей"
	ns.L["Carve"] = "Разделка туши"
	ns.L["Chimera Shot"] = "Выстрел химеры"
	ns.L["Cobra Strikes"] = "Бросок кобры"
	ns.L["Explosive Shot"] = "Разрывной выстрел"
	ns.L["Flanking Strike"] = "Обходной удар"
	ns.L["Heart of the Lion"] = "Львиное сердце"
	ns.L["Kill Command"] = "Команда \"Взять!\""
	ns.L["Lone Wolf"] = "Одинокий волк"
	ns.L["Master Marksman"] = "Мастер стрельбы"
	ns.L["Serpent Spread"] = "Распространяющийся укус"
	ns.L["Sniper Training"] = "Навыки снайпера"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "Дух гадюки"
	ns.L["Dual Wield Specialization"] = "Специализация на бое с оружием в обеих руках"
	ns.L["Expose Weakness"] = "Выявление слабости"
	ns.L["Invigoration"] = "Окрыление"
	ns.L["Melee Specialist"] = "Специалист по ближнему бою"
	ns.L["Steady Shot"] = "Верный выстрел"
	ns.L["Trap Launcher"] = "Бросок ловушки"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "Чародейская вспышка"
	ns.L["Arcane Surge"] = "Чародейский выброс"
	ns.L["Burnout"] = "Выгорание"
	ns.L["Enlightenment"] = "Просветление"
	ns.L["Fingers of Frost"] = "Ледяные пальцы"
	ns.L["Ice Lance"] = "Ледяное копье"
	ns.L["Icy Veins"] = "Стылая кровь"
	ns.L["Living Bomb"] = "Живая бомба"
	ns.L["Living Flame"] = "Живой жар"
	ns.L["Mass Regeneration"] = "Массовая регенерация"
	ns.L["Regeneration"] = "Регенерация"
	ns.L["Rewind Time"] = "Перемотка времени"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "Заморозка мозгов"
	ns.L["Chronostatic Preservation"] = "Темпоральное спасение"
	ns.L["Expanded Intellect"] = "Развитый интеллект"
	ns.L["Frostfire Bolt"] = "Стрела ледяного огня"
	ns.L["Hot Streak"] = "Полоса везения"
	ns.L["Missile Barrage"] = "Заградительные стрелы"
	ns.L["Spell Power"] = "Сила заклинаний"
	ns.L["Spellfrost Bolt"] = "Стрела чар льда"
	-- Paladin Phase 1
	ns.L["Aegis"] = "Эгида"
	ns.L["Avenger's Shield"] = "Щит мстителя"
	ns.L["Beacon of Light"] = "Частица Света"
	ns.L["Crusader Strike"] = "Удар воина Света"
	ns.L["Exorcist"] = "Экзорцист"
	ns.L["Divine Sacrifice"] = "Священная жертва"
	ns.L["Divine Storm"] = "Божественная буря"
	ns.L["Hand of Reckoning"] = "Длань возмездия"
	ns.L["Horn of Lordaeron"] = "Горн Лордерона"
	ns.L["Inspiration Exemplar"] = "Пример для подражания"
	ns.L["Rebuke"] = "Укор"
	ns.L["Seal of Martyrdom"] = "Печать мученичества"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "Усиленные благословения"
	ns.L["Enlightened Judgements"] = "Просветленное суждение"
	ns.L["Guarded by the Light"] = "Под охраной света"
	ns.L["Infusion of Light"] = "Прилив Света"
	ns.L["Sacred Shield"] = "Священный щит"
	ns.L["Sheath of Light"] = "Покров Света"
	ns.L["The Art of War"] = "Искусство войны"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "Круг исцеления"
	ns.L["Homunculi"] = "Гомункулы"
	ns.L["Mind Sear"] = "Иссушение разума"
	ns.L["Penance"] = "Исповедь"
	ns.L["Power Word: Barrier"] = "Слово Силы: Барьер"
	ns.L["Prayer of Mending"] = "Молитва восстановления"
	ns.L["Serendipity"] = "Прозорливость"
	ns.L["Shadow Word: Death"] = "Слово Тьмы: Смерть"
	ns.L["Shared Pain"] = "Общая боль"
	ns.L["Strength of Soul"] = "Сила души"
	ns.L["Twisted Faith"] = "Обман разума"
	ns.L["Void Plague"] = "Чума Бездны"
	-- Priest Phase 2
	ns.L["Dispersion"] = "Слияние с Тьмой"
	ns.L["Empowered Renew"] = "Усиленное обновление"
	ns.L["Increased Fortitude"] = "Повышенная стойкость"
	ns.L["Mind Spike"] = "Пронзание разума"
	ns.L["Pain Suppression"] = "Подавление боли"
	ns.L["Renewed Hope"] = "Новая надежда"
	ns.L["Shadowfiend"] = "Исчадие Тьмы"
	ns.L["Spirit of the Redeemer"] = "Дух воздаяния"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "Промеж глаз"
	ns.L["Blade Dance"] = "Танец клинков"
	ns.L["Deadly Brew"] = "Смертельное варево"
	ns.L["Envenom"] = "Отравление"
	ns.L["Just a Flesh Wound"] = "Просто царапина"
	ns.L["Main Gauche"] = "Главный аргумент"
	ns.L["Mutilate"] = "Расправа"
	ns.L["Quick Draw"] = "Быстрая реакция"
	ns.L["Saber Slash"] = "Удар саблей"
	ns.L["Shadowstrike"] = "Теневой удар"
	ns.L["Slaughter from the Shadows"] = "Резня во тьме"
	ns.L["Shiv"] = "Отравляющий укол"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "Мастер скрытности"
	ns.L["Poisoned Knife"] = "Отравленный нож"
	ns.L["Redirect"] = "Перенаправление"
	ns.L["Rolling with the Punches"] = "Держать удар"
	ns.L["Shadowstep"] = "Шаг сквозь тень"
	ns.L["Shuriken Toss"] = "Бросок сюрикэна"
	ns.L["Waylay"] = "Засада"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "Наставления предков"
	ns.L["Dual Wield Specialization"] = "Специализация на бое с оружием в обеих руках"
	ns.L["Earth Shield"] = "Щит земли"
	ns.L["Healing Rain"] = "Целительный ливень"
	ns.L["Lava Burst"] = "Выброс лавы"
	ns.L["Lava Lash"] = "Вскипание лавы"
	ns.L["Molten Blast"] = "Всплеск лавы"
	ns.L["Overload"] = "Перегрузка"
	ns.L["Shamanistic Rage"] = "Ярость шамана"
	ns.L["Shield Mastery"] = "Мастерское владение щитом"
	ns.L["Way of Earth"] = "Путь земли"
	ns.L["Water Shield"] = "Водный щит"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "Пробуждение предка"
	ns.L["Decoy Totem"] = "Тотем-приманка"
	ns.L["Fire Nova"] = "Кольцо огня"
	ns.L["Maelstrom Weapon"] = "Оружие Водоворота"
	ns.L["Power Surge"] = "Волна силы"
	ns.L["Spirit of the Alpha"] = "Дух вожака стаи"
	ns.L["Totemic Projection"] = "Проецирование тотемов"
	ns.L["Two-Handed Mastery"] = "Мастер двуручного оружия"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "Стрела Хаоса"
	ns.L["Demonic Grace"] = "Демоническая грация"
	ns.L["Demonic Pact"] = "Демонический союз"
	ns.L["Demonic Tactics"] = "Власть над демонами"
	ns.L["Everlasting Affliction"] = "Беспрерывное колдовство"
	ns.L["Haunt"] = "Блуждающий дух"
	ns.L["Incinerate"] = "Испепеление"
	ns.L["Lake of Fire"] = "Огненное озеро"
	ns.L["Master Channeler"] = "Мастер-чаротворец"
	ns.L["Metamorphosis"] = "Метаморфоза"
	ns.L["Shadow Bolt Volley"] = "Залп стрел Тьмы"
	ns.L["Soul Siphon"] = "Вытягивание души"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "Гибельный танец"
	ns.L["Demonic Knowledge"] = "Демоническое знание"
	ns.L["Grimoire of Synergy"] = "Гримуар у"
	ns.L["Invocation"] = "Заклятие"
	ns.L["Portal of Summoning"] = "Портал призыва"
	ns.L["Shadow and Flame"] = "Тьма и пламя"
	ns.L["Shadowflame"] = "Пламя Тьмы"
	ns.L["Soul Harvesting"] = "Жатва душ"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "Кровавое бешенство"
	ns.L["Consumed by Rage"] = "Неконтролируемая ярость"
	ns.L["Devastate"] = "Сокрушение"
	ns.L["Endless Rage"] = "Бесконечная ярость"
	ns.L["Flagellation"] = "Флагелляция"
	ns.L["Frenzied Assault"] = "Неистовый натиск"
	ns.L["Furious Thunder"] = "Неистовый гром"
	ns.L["Quick Strike"] = "Быстрый удар迅捷打击"
	ns.L["Raging Blow"] = "Яростный выпад"
	ns.L["Single-Minded Fury"] = "Свирепая неистовость"
	ns.L["Victory Rush"] = "Победный раж"
	ns.L["Warbringer"] = "Вестник войны"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "Всплеск крови"
	ns.L["Commanding Shout"] = "Командирский крик"
	ns.L["Enraged Regeneration"] = "Безудержное восстановление"
	ns.L["Focused Rage"] = "Сосредоточенная ярость"
	ns.L["Intervene"] = "Вмешательство"
	ns.L["Precise Timing"] = "Точный расчет"
	ns.L["Rallying Cry"] = "Ободряющий клич"

elseif ns.locale == "zhCN" then
	ns.L["AddOn Description"] = "所有 SoD 符文。 （和更多！）。"
	ns.L["Arcane"] = "奥术"
	ns.L["Demonic"] = "恶魔"
	ns.L["Duty"] = "义务"
	ns.L["Hide if learnt"] = "如果学习了符文则隐藏"
	ns.L["Map Pin"] = "地图图钉"
	ns.L["Mjolnir"] = "雷神"
	ns.L["Phase 1 Summary"] = "第一阶段总结"
	ns.L["Phase 2 Summary"] = "第二阶段总结"
	ns.L["Runes"] = "符文"
	ns.L["Skill Book"] = "技能书"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "怒风之怒"
	ns.L["Lacerate"] = "割伤"
	ns.L["Lifebloom"] = "生命绽放"
	ns.L["Living Seed"] = "生命之种"
	ns.L["Mangle"] = "割碎"
	ns.L["Savage Roar"] = "野蛮咆哮"
	ns.L["Skull Bash"] = "迎头痛击"
	ns.L["Starsurge"] = "星涌术"
	ns.L["Sunfire"] = "阳炎术"
	ns.L["Survival of the Fittest"] = "优胜劣汰"
	ns.L["Wild Growth"] = "野性成长"
	ns.L["Wild Strikes"] = "狂野打击"
	-- Druid Phase 2
	ns.L["Berserk"] = "狂暴"
	ns.L["Deeper Wilds"] = "野性深远"
	ns.L["Dreamstate"] = "迷梦"
	ns.L["Eclipse"] = "日月之蚀"
	ns.L["Enhanced Restoration"] = "强化恢复"
	ns.L["King of the Jungle"] = "丛林之王"
	ns.L["Nourish"] = "滋养"
	ns.L["Revive"] = "起死回生"
	ns.L["Survival Instincts"] = "生存本能"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "野兽控制"
	ns.L["Carve"] = "削凿"
	ns.L["Chimera Shot"] = "奇美拉射击"
	ns.L["Cobra Strikes"] = "眼镜蛇打击"
	ns.L["Explosive Shot"] = "爆炸射击"
	ns.L["Flanking Strike"] = "侧翼打击"
	ns.L["Heart of the Lion"] = "雄狮之心"
	ns.L["Kill Command"] = "杀戮命令"
	ns.L["Lone Wolf"] = "独来独往"
	ns.L["Master Marksman"] = "神射手"
	ns.L["Serpent Spread"] = "毒蛇扩散"
	ns.L["Sniper Training"] = "狙击训练"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "蝰蛇守护"
	ns.L["Dual Wield Specialization"] = "双武器专精"
	ns.L["Expose Weakness"] = "破甲虚弱"
	ns.L["Invigoration"] = "鼓舞"
	ns.L["Melee Specialist"] = "近战专家"
	ns.L["Steady Shot"] = "稳固射击"
	ns.L["Trap Launcher"] = "陷阱发射器"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "奥术冲击"
	ns.L["Arcane Surge"] = "奥术涌动"
	ns.L["Burnout"] = "燃尽"
	ns.L["Enlightenment"] = "启迪"
	ns.L["Fingers of Frost"] = "寒冰指"
	ns.L["Ice Lance"] = "冰枪术"
	ns.L["Icy Veins"] = "冰冷血脉"
	ns.L["Living Bomb"] = "活动炸弹"
	ns.L["Living Flame"] = "活体烈焰"
	ns.L["Mass Regeneration"] = "群体再生"
	ns.L["Regeneration"] = "再生"
	ns.L["Rewind Time"] = "时光倒转"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "冰冷智慧"
	ns.L["Chronostatic Preservation"] = "凝时恩护"
	ns.L["Expanded Intellect"] = "智慧延展"
	ns.L["Frostfire Bolt"] = "霜火之箭"
	ns.L["Hot Streak"] = "炽热连击"
	ns.L["Missile Barrage"] = "飞弹连射"
	ns.L["Spell Power"] = "法术强权"
	ns.L["Spellfrost Bolt"] = "法术冰霜箭"
	-- Paladin Phase 1
	ns.L["Aegis"] = "神盾"
	ns.L["Avenger's Shield"] = "复仇者之盾"
	ns.L["Beacon of Light"] = "圣光道标"
	ns.L["Crusader Strike"] = "十字军打击"
	ns.L["Exorcist"] = "驱魔人"
	ns.L["Divine Sacrifice"] = "神圣牺牲"
	ns.L["Divine Storm"] = "神圣风暴"
	ns.L["Hand of Reckoning"] = "清算之手"
	ns.L["Horn of Lordaeron"] = "洛丹伦号角"
	ns.L["Inspiration Exemplar"] = "激励典范"
	ns.L["Rebuke"] = "责难"
	ns.L["Seal of Martyrdom"] = "殉道圣印"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "强化祝福"
	ns.L["Enlightened Judgements"] = "开明审判"
	ns.L["Guarded by the Light"] = "圣光守护"
	ns.L["Infusion of Light"] = "圣光灌注"
	ns.L["Sacred Shield"] = "圣洁护盾"
	ns.L["Sheath of Light"] = "圣光出鞘"
	ns.L["The Art of War"] = "战争艺术"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "治疗之环"
	ns.L["Homunculi"] = "裂魂魔"
	ns.L["Mind Sear"] = "精神灼烧"
	ns.L["Penance"] = "苦修"
	ns.L["Power Word: Barrier"] = "真言术：障"
	ns.L["Prayer of Mending"] = "愈合祷言"
	ns.L["Serendipity"] = "妙手回春"
	ns.L["Shadow Word: Death"] = "暗言术：灭"
	ns.L["Shared Pain"] = "分担痛苦"
	ns.L["Strength of Soul"] = "灵魂之力"
	ns.L["Twisted Faith"] = "扭曲信仰"
	ns.L["Void Plague"] = "虚空疫病"
	-- Priest Phase 2
	ns.L["Dispersion"] = "消散"
	ns.L["Empowered Renew"] = "恢复增效"
	ns.L["Increased Fortitude"] = "强化坚韧"
	ns.L["Mind Spike"] = "心灵尖刺"
	ns.L["Pain Suppression"] = "痛苦压制"
	ns.L["Renewed Hope"] = "新生希望"
	ns.L["Shadowfiend"] = "暗影魔"
	ns.L["Spirit of the Redeemer"] = "救赎者之魂"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "正中眉心"
	ns.L["Blade Dance"] = "刃舞"
	ns.L["Deadly Brew"] = "致命阴谋"
	ns.L["Envenom"] = "毒伤"
	ns.L["Just a Flesh Wound"] = "只是皮肉伤"
	ns.L["Main Gauche"] = "左右开弓"
	ns.L["Mutilate"] = "毁伤"
	ns.L["Quick Draw"] = "速射"
	ns.L["Saber Slash"] = "军刀猛刺"
	ns.L["Shadowstrike"] = "暗影打击"
	ns.L["Slaughter from the Shadows"] = "暗影杀手"
	ns.L["Shiv"] = "毒刃"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "敏锐大师"
	ns.L["Poisoned Knife"] = "剧毒之刃"
	ns.L["Redirect"] = "转嫁"
	ns.L["Rolling with the Punches"] = "闪转腾挪"
	ns.L["Shadowstep"] = "暗影步"
	ns.L["Shuriken Toss"] = "飞镖投掷"
	ns.L["Waylay"] = "埋伏"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "先祖指引"
	ns.L["Dual Wield Specialization"] = "双武器专精"
	ns.L["Earth Shield"] = "大地之盾"
	ns.L["Healing Rain"] = "治疗之雨"
	ns.L["Lava Burst"] = "熔岩爆裂"
	ns.L["Lava Lash"] = "熔岩猛击"
	ns.L["Molten Blast"] = "熔火爆裂"
	ns.L["Overload"] = "过载"
	ns.L["Shamanistic Rage"] = "萨满之怒"
	ns.L["Shield Mastery"] = "盾牌精通"
	ns.L["Way of Earth"] = "土之道"
	ns.L["Water Shield"] = "水之护盾"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "先祖复苏"
	ns.L["Decoy Totem"] = "诱饵图腾"
	ns.L["Fire Nova"] = "火焰新星"
	ns.L["Maelstrom Weapon"] = "漩涡武器"
	ns.L["Power Surge"] = "能量涌动"
	ns.L["Spirit of the Alpha"] = "头狼之魂"
	ns.L["Totemic Projection"] = "图腾投射"
	ns.L["Two-Handed Mastery"] = "双手精通"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "混乱之箭"
	ns.L["Demonic Grace"] = "恶魔优雅"
	ns.L["Demonic Pact"] = "恶魔契约"
	ns.L["Demonic Tactics"] = "恶魔战术"
	ns.L["Everlasting Affliction"] = "持久痛苦"
	ns.L["Haunt"] = "鬼影缠身"
	ns.L["Incinerate"] = "烧尽"
	ns.L["Lake of Fire"] = "火焰之湖"
	ns.L["Master Channeler"] = "引导大师"
	ns.L["Metamorphosis"] = "恶魔变形"
	ns.L["Shadow Bolt Volley"] = "暗影箭雨"
	ns.L["Soul Siphon"] = "灵魂虹吸"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "堕落之舞"
	ns.L["Demonic Knowledge"] = "恶魔知识"
	ns.L["Grimoire of Synergy"] = "协同魔典"
	ns.L["Invocation"] = "祈告"
	ns.L["Portal of Summoning"] = "召唤传送门"
	ns.L["Shadow and Flame"] = "影与焰"
	ns.L["Shadowflame"] = "暗影烈焰"
	ns.L["Soul Harvesting"] = "灵魂收割"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "血之狂暴"
	ns.L["Consumed by Rage"] = "噬心狂怒"
	ns.L["Devastate"] = "毁灭打击"
	ns.L["Endless Rage"] = "无尽怒气"
	ns.L["Flagellation"] = "狂热鞭笞"
	ns.L["Frenzied Assault"] = "狂乱攻击"
	ns.L["Furious Thunder"] = "狂怒雷霆"
	ns.L["Quick Strike"] = "迅捷打击"
	ns.L["Raging Blow"] = "怒击"
	ns.L["Single-Minded Fury"] = "鲁莽怒火"
	ns.L["Victory Rush"] = "乘胜追击"
	ns.L["Warbringer"] = "战神"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "血涌"
	ns.L["Commanding Shout"] = "命令怒吼"
	ns.L["Enraged Regeneration"] = "狂怒回复"
	ns.L["Focused Rage"] = "怒火聚焦"
	ns.L["Intervene"] = "援护"
	ns.L["Precise Timing"] = "精准猛击"
	ns.L["Rallying Cry"] = "集结呐喊"

elseif ns.locale == "zhTW" then
	ns.L["AddOn Description"] = "所有 SoD 符文。 （和更多！）。"
	ns.L["Arcane"] = "奧術"
	ns.L["Demonic"] = "惡魔"
	ns.L["Duty"] = "義務"
	ns.L["Hide if learnt"] = "如果學習了符文則隱藏"
	ns.L["Map Pin"] = "地圖圖釘"
	ns.L["Mjolnir"] = "雷神"
	ns.L["Phase 1 Summary"] = "第一階段總結"
	ns.L["Phase 2 Summary"] = "第二階段總結"
	ns.L["Runes"] = "符文"
	ns.L["Skill Book"] = "技能書"
	-- Druid Phase 1
	ns.L["Fury of Stormrage"] = "怒風之怒"
	ns.L["Lacerate"] = "割傷"
	ns.L["Lifebloom"] = "生命綻放"
	ns.L["Living Seed"] = "生命之種"
	ns.L["Mangle"] = "割碎"
	ns.L["Savage Roar"] = "野蠻咆哮"
	ns.L["Skull Bash"] = "迎頭痛擊"
	ns.L["Starsurge"] = "星湧術"
	ns.L["Sunfire"] = "陽炎術"
	ns.L["Survival of the Fittest"] = "優勝劣汰"
	ns.L["Wild Growth"] = "野性成長"
	ns.L["Wild Strikes"] = "狂野打擊"
	-- Druid Phase 2
	ns.L["Berserk"] = "狂暴"
	ns.L["Deeper Wilds"] = "野性深遠"
	ns.L["Dreamstate"] = "迷夢"
	ns.L["Eclipse"] = "日月之蝕"
	ns.L["Enhanced Restoration"] = "強化恢復"
	ns.L["King of the Jungle"] = "叢林之王"
	ns.L["Nourish"] = "滋養"
	ns.L["Revive"] = "起死回生"
	ns.L["Survival Instincts"] = "生存本能"
	-- Hunter Phase 1
	ns.L["Beast Mastery"] = "野獸控制"
	ns.L["Carve"] = "削鑿"
	ns.L["Chimera Shot"] = "奇美拉射擊"
	ns.L["Cobra Strikes"] = "眼鏡蛇打擊"
	ns.L["Explosive Shot"] = "爆炸射擊"
	ns.L["Flanking Strike"] = "側翼打擊"
	ns.L["Heart of the Lion"] = "雄獅之心"
	ns.L["Kill Command"] = "殺戮命令"
	ns.L["Lone Wolf"] = "獨來獨往"
	ns.L["Master Marksman"] = "神射手"
	ns.L["Serpent Spread"] = "毒蛇擴散"
	ns.L["Sniper Training"] = "狙擊訓練"
	-- Hunter Phase 2
	ns.L["Aspect of the Viper"] = "蝰蛇守護"
	ns.L["Dual Wield Specialization"] = "雙武器專精"
	ns.L["Expose Weakness"] = "破甲虛弱"
	ns.L["Invigoration"] = "鼓舞"
	ns.L["Melee Specialist"] = "近戰專家"
	ns.L["Steady Shot"] = "穩固射擊"
	ns.L["Trap Launcher"] = "陷阱發射器"
	-- Mage Phase 1
	ns.L["Arcane Blast"] = "奧術衝擊"
	ns.L["Arcane Surge"] = "奧術湧動"
	ns.L["Burnout"] = "燃盡"
	ns.L["Enlightenment"] = "啟迪"
	ns.L["Fingers of Frost"] = "寒冰指"
	ns.L["Ice Lance"] = "冰槍術"
	ns.L["Icy Veins"] = "冰冷血脈"
	ns.L["Living Bomb"] = "活動炸彈"
	ns.L["Living Flame"] = "活體烈焰"
	ns.L["Mass Regeneration"] = "群體再生"
	ns.L["Regeneration"] = "再生"
	ns.L["Rewind Time"] = "時光倒轉"
	-- Mage Phase 2
	ns.L["Brain Freeze"] = "冰冷智慧"
	ns.L["Chronostatic Preservation"] = "凝時恩護"
	ns.L["Expanded Intellect"] = "智慧延展"
	ns.L["Frostfire Bolt"] = "霜火之箭"
	ns.L["Hot Streak"] = "熾熱連擊"
	ns.L["Missile Barrage"] = "飛彈連射"
	ns.L["Spell Power"] = "法術強權"
	ns.L["Spellfrost Bolt"] = "法術冰霜箭"
	-- Paladin Phase 1
	ns.L["Aegis"] = "神盾"
	ns.L["Avenger's Shield"] = "復仇者之盾"
	ns.L["Beacon of Light"] = "聖道標"
	ns.L["Crusader Strike"] = "十字軍打擊"
	ns.L["Exorcist"] = "驅魔人"
	ns.L["Divine Sacrifice"] = "神聖犧牲"
	ns.L["Divine Storm"] = "神聖風暴"
	ns.L["Hand of Reckoning"] = "清算之手"
	ns.L["Horn of Lordaeron"] = "洛丹倫號角"
	ns.L["Inspiration Exemplar"] = "激勵典範"
	ns.L["Rebuke"] = "責難"
	ns.L["Seal of Martyrdom"] = "殉道聖印"
	-- Paladin Phase 2
	ns.L["Enhanced Blessings"] = "強化祝福"
	ns.L["Enlightened Judgements"] = "開明審判"
	ns.L["Guarded by the Light"] = "聖光守護"
	ns.L["Infusion of Light"] = "聖光灌注"
	ns.L["Sacred Shield"] = "聖潔護盾"
	ns.L["Sheath of Light"] = "聖光出鞘"
	ns.L["The Art of War"] = "戰爭藝術"
	-- Priest Phase 1
	ns.L["Circle of Healing"] = "治療之環"
	ns.L["Homunculi"] = "裂魂魔"
	ns.L["Mind Sear"] = "精神灼燒"
	ns.L["Penance"] = "苦修"
	ns.L["Power Word: Barrier"] = "真言術：障"
	ns.L["Prayer of Mending"] = "癒合禱言"
	ns.L["Serendipity"] = "妙手回春"
	ns.L["Shadow Word: Death"] = "暗言術：滅"
	ns.L["Shared Pain"] = "分擔痛苦"
	ns.L["Strength of Soul"] = "靈魂之力"
	ns.L["Twisted Faith"] = "扭曲信仰"
	ns.L["Void Plague"] = "虛空疫病"
	-- Priest Phase 2
	ns.L["Dispersion"] = "消散"
	ns.L["Empowered Renew"] = "恢復增效"
	ns.L["Increased Fortitude"] = "強化堅韌"
	ns.L["Mind Spike"] = "心靈尖刺"
	ns.L["Pain Suppression"] = "痛苦壓制"
	ns.L["Renewed Hope"] = "新生希望"
	ns.L["Shadowfiend"] = "暗影魔"
	ns.L["Spirit of the Redeemer"] = "救贖者之魂"
	-- Rogue Phase 1
	ns.L["Between the Eyes"] = "正中眉心"
	ns.L["Blade Dance"] = "刃舞"
	ns.L["Deadly Brew"] = "致命陰謀"
	ns.L["Envenom"] = "毒傷"
	ns.L["Just a Flesh Wound"] = "只是皮肉傷"
	ns.L["Main Gauche"] = "左右開弓"
	ns.L["Mutilate"] = "毀傷"
	ns.L["Quick Draw"] = "速射"
	ns.L["Saber Slash"] = "軍刀猛刺"
	ns.L["Shadowstrike"] = "暗影打擊"
	ns.L["Slaughter from the Shadows"] = "暗影殺手"
	ns.L["Shiv"] = "毒刃"
	-- Rogue Phase 2
	ns.L["Master of Subtlety"] = "敏銳大師"
	ns.L["Poisoned Knife"] = "劇毒之刃"
	ns.L["Redirect"] = "轉嫁"
	ns.L["Rolling with the Punches"] = "閃轉騰挪"
	ns.L["Shadowstep"] = "暗影步"
	ns.L["Shuriken Toss"] = "飛鏢投擲"
	ns.L["Waylay"] = "埋伏"
	-- Shaman Phase 1
	ns.L["Ancestral Guidance"] = "先祖指引"
	ns.L["Dual Wield Specialization"] = "雙武器專精"
	ns.L["Earth Shield"] = "大地之盾"
	ns.L["Healing Rain"] = "治療之雨"
	ns.L["Lava Burst"] = "熔岩爆裂"
	ns.L["Lava Lash"] = "熔岩猛擊"
	ns.L["Molten Blast"] = "熔火爆裂"
	ns.L["Overload"] = "過載"
	ns.L["Shamanistic Rage"] = "薩滿之怒"
	ns.L["Shield Mastery"] = "盾牌精通"
	ns.L["Way of Earth"] = "土之道"
	ns.L["Water Shield"] = "水之護盾"
	-- Shaman Phase 2
	ns.L["Ancestral Awakening"] = "先祖復甦"
	ns.L["Decoy Totem"] = "誘餌圖騰"
	ns.L["Fire Nova"] = "火焰新星"
	ns.L["Maelstrom Weapon"] = "漩渦武器"
	ns.L["Power Surge"] = "能量湧動"
	ns.L["Spirit of the Alpha"] = "頭狼之魂"
	ns.L["Totemic Projection"] = "圖騰投射"
	ns.L["Two-Handed Mastery"] = "雙手精通"
	-- Warlock Phase 1
	ns.L["Chaos Bolt"] = "混亂之箭"
	ns.L["Demonic Grace"] = "惡魔優雅"
	ns.L["Demonic Pact"] = "惡魔契約"
	ns.L["Demonic Tactics"] = "惡魔戰術"
	ns.L["Everlasting Affliction"] = "持久痛苦"
	ns.L["Haunt"] = "鬼影纏身"
	ns.L["Incinerate"] = "燒盡"
	ns.L["Lake of Fire"] = "火焰之湖"
	ns.L["Master Channeler"] = "引導大師"
	ns.L["Metamorphosis"] = "惡魔變形"
	ns.L["Shadow Bolt Volley"] = "暗影箭雨"
	ns.L["Soul Siphon"] = "靈魂虹吸"
	-- Warlock Phase 2
	ns.L["Dance of the Wicked"] = "墮落之舞"
	ns.L["Demonic Knowledge"] = "惡魔知識"
	ns.L["Grimoire of Synergy"] = "協同魔典"
	ns.L["Invocation"] = "祈告"
	ns.L["Portal of Summoning"] = "召喚傳送門"
	ns.L["Shadow and Flame"] = "影與焰"
	ns.L["Shadowflame"] = "暗影烈焰"
	ns.L["Soul Harvesting"] = "靈魂收割"
	-- Warrior Phase 1
	ns.L["Blood Frenzy"] = "血之狂暴"
	ns.L["Consumed by Rage"] = "噬心狂怒"
	ns.L["Devastate"] = "毀滅打擊"
	ns.L["Endless Rage"] = "無盡怒氣"
	ns.L["Flagellation"] = "狂熱鞭笞"
	ns.L["Frenzied Assault"] = "狂亂攻擊"
	ns.L["Furious Thunder"] = "狂怒雷霆"
	ns.L["Quick Strike"] = "迅捷打擊"
	ns.L["Raging Blow"] = "怒擊"
	ns.L["Single-Minded Fury"] = "魯莽怒火"
	ns.L["Victory Rush"] = "乘勝追擊"
	ns.L["Warbringer"] = "戰神"
	-- Warrior Phase 2
	ns.L["Blood Surge"] = "血湧"
	ns.L["Commanding Shout"] = "命令怒吼"
	ns.L["Enraged Regeneration"] = "狂怒回覆"
	ns.L["Focused Rage"] = "怒火聚焦"
	ns.L["Intervene"] = "援助"
	ns.L["Precise Timing"] = "精準猛擊"
	ns.L["Rallying Cry"] = "集結吶喊"
	ns.L["Rallying Cry"] = "集結吶喊"

else
	ns.L["AddOn Description"] = "All the SoD Runes. (And more!)"
	ns.L["Hide if learnt"] = "Hide if the rune was learnt"
end